apiVersion: v1
kind: Secret
metadata:
  name: zot-htpasswd
  namespace: zot
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:1Zim8qw=,iv:AFdb7lUmFl8u3XEj4dZHWAH/9qmzPcFBZPbKKQyO0K0=,tag:b8nKSym4mwKAcb+N+U7jSg==,type:str]
  password: ENC[AES256_GCM,data:WQTaM+b0Nwy9ItqvlyPDJ3STO0RYxA1jVFprjz4G/mg=,iv:mFwAT9d0Rc2e9aJcbLPstLtSgVmgkmIi5EF4XTVtxDU=,tag:LWuprTwHCaVBMAfgZI1u+w==,type:str]
  htpasswd: ENC[AES256_GCM,data:GB7dWRtT7ilDqOoF3owT/sODASDfzwh+/IRrQtLOup48FVCdQlRekJg/y9GLs8DI81bk9ADKcu0a6jV/utktbFI/Lg==,iv:MdVLKjjik1lM78RcQWeEKyjQm1oBWEbBAMe4/nK5cTE=,tag:2LmhRLZO4/K2T7sqgr5uBA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNlNvc0pQK0g1amkzYXlB
        N1dIc0VUQnJVem1hMEtKdHpnTzRaOUVzcXhRCi94a25CZnlXSWVETXRiSEpLWUR3
        VHU3aUdhRU9yQ2JsN1dWNTU4ZjdZUlEKLS0tIEtlMDlxZTJYK3JGaFk1WU5pODZz
        THJ4aWNiWWdZWlVvT1VZRmxZR1V6KzgKtDBMv6E0XPU3ZzIWSA1KSUzPG61P7S5j
        xksmqf5q5+Qi3QguZRj2byIBIE49/9rtu1KQwh6rXeO4+VG3VDmUDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T21:40:39Z"
  mac: ENC[AES256_GCM,data:CQv0lCDDjUhlBZoivgyHnzV6nnfImShA+OxjwSpmwdTIHbSeFmDJVM48w9aCpbd9WlsYP0xfnMLmC6Jfdd5dAHff2CEsoCVZRbNx/EePlzFDsCx5ZVqOvr2UHXsSChEIT63PgR52VMamosV55umrZFL5ZkZBGSE0rMBY2nWKz/M=,iv:KuKT/QiF5nM3nhrvqIvz+3tlC9bScl5U1ynoymqDn3s=,tag:j+7ZDfiapsuMMWX2rZDHCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
