apiVersion: v1
kind: Secret
metadata:
  name: autokuma-secrets
  namespace: uptime-kuma
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:KAymAnM=,iv:6NtjON7OS08rDTC6XWItHkDMekMeHnvUNqhw/JN6GLs=,tag:Ybr8Wyg1HFackCtMH9r1iA==,type:str]
  password: ENC[AES256_GCM,data:NKg1Ak++1HvmG4XY1KMu,iv:Cxc3OLCJSbwZMUn7AI9mwJ5KFKQc9AozzWhLFd+gRYc=,tag:/RGAt+U/Wk2R/56hd+N6FQ==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlNLd3VIdWV0UkQ3QkFL
        eUhReVY4WGE1a1ltK0ZET3pNaXVManIxbXlrCmtGcXJSTzhFNTIwR20weXNFdnJQ
        VmwwaTQxaDA5MXcrTkp3by8zblh4Y1EKLS0tICtSTzZOQndGM3BsbUl3c21TamFa
        MkJDZFNycGJpV2RmU2F6OEYwWDVqTkEK5YmApXijANSJmb9tRoYldeXQsyEXDQr+
        Yurmklk++U/pscBtXKIRkQffwvy3V6SkMswXbp8Fi/E4EWkcG5NH7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T11:53:10Z"
  mac: ENC[AES256_GCM,data:MAzcImoKiMXTahwOKbg99LVwQyacqvOo1UswkkGQMvdDYHCD1zzRjKmlYfYQHS9IhK/b6xSLJHnxm3Dq+IOkkMgA2+ovVL+HOJsMxASlyf7DwlnbjxmB/PR53/CQBKkEzXiP5DdUw0eS5H3oZ5UNRLlM1TazeAekbxQ3iZrlHfc=,iv:PvfoOWhdEQJC5QTKz+2Ff6wNNNng8jiqvS/KG5C7tlA=,tag:btnT3VtedvTDU96ApZZ7bA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
