apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: rustfs
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:ja15fjvAbVMZ3b0B,iv:jRRU7lRyBnugfkVy82Su6SYBj8v6Sq4saz+1QNrEtDE=,tag:4U2nEStv/cv3oLbOUqk5DQ==,type:str]
  secret-key: ENC[AES256_GCM,data:ZTfxoL0h8Gb7ipDi2yDowxolcwMc35it1hXp56PODPyLhWeYrKfFlA==,iv:Q2bP+/iHrjVOp20VGXHbBnYxtXRZP4lOcQTL1H9z7F8=,tag:S8YYZOYe0dJtZdL4S67Ftg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUk5YWk1PSEg4MkVqVTc1
        bURRNDFrVlNrZVlRYzNsclZKVVlRWDlQRmlFClk0VVRRcjdWaitISkxNSDFVQkRr
        bWFQVGhlV2p1WGRTcGYwMjhYdUhMUHcKLS0tIDZVWUxRNFYxWmlsVURaN3FETi8x
        U0pUN2VRankzMk83R213aGRDMFNDWlEKxDAQKTt6JQOseCiXorcZ90jhdDV0ml9R
        RC3NCNik0qxg/MucxzdtWbCDBRR8ur0zO1m2VBiMkxrMsL75JtOb8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T12:48:18Z"
  mac: ENC[AES256_GCM,data:4b383d+K3q5lZBO0Dlq2WDf/cXlKM3b5FozMI4zji1JYUAnFQPCJjcxv9kTN2w6o+qXQVb5fchPkCu0dV0Av0yAhxydkvi/He5OJ/sm8k+whDqa7puJB9fixyKSES2bcpXFFjkysUzg7lUa3Z+4lmas4zJlKQ9u3qfTfHyxjmzo=,iv:k29nsXZDRsFcW4nshBZsAag5PAzBPTWKwQ26YEd38hY=,tag:JX1L/Z4FsiHR1UH24ESVNA==,type:str]
  version: 3.13.0
