apiVersion: v1
kind: Secret
metadata:
  name: rustfs-oidc-credentials
  namespace: rustfs
type: Opaque
stringData:
  client_secret: ENC[AES256_GCM,data:8G4jvJoJhts14iWPQelxate7uLKrExPDL8J3l/gYJmzx+ifXY/aIAOb0228NGe/qdbEBPaAWWDXRUHScBb+pFA==,iv:CMEG9iE46eN22nwE/8Aq4D1medWvJUvfaiQ3LyNH2qk=,tag:+ka4y2rb/7pVrzug9Ca6Mg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscm1jY2V1WGR0aUpiZjZp
        Y2ZQb2hyaU83b0JRNXh0UzBjcGJlSVFVK1NrCks1VU5ERHhGc2t4QjB6VkdEUDBx
        cDRHQWJqMzJQMGtDMnJrKzhKQVFvdTAKLS0tIEpDUkpVL1duOFZobkNDcVVHUmkv
        cXhwTjhoTW1KWEFSb0hUT21zRjNOKzAK5v+9n+/YW51oocSE1kIR0SEAxS66KSMn
        T5ze9dLQPaYbgdLP4mq0kIBqcCRDTH509j8RypmogwVsH6E7/312WA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T17:02:47Z"
  mac: ENC[AES256_GCM,data:M00grC/ehGeDxuzmWeUM6Ux3V1H1p/hjS0bWEXm9sSpKRnQRBk6ehBcBVLinbgMn3qPoJ7KWM2fy9nZRIzgtO3S0qtan7RFcK+wwA6hqCEfFMZ016OK6fvGv7bSBlgDE1y11aLt5tJIX6iWFEZ/xSe8zwf1iLhUyOHzWh0b5Kf8=,iv:+m7aTdisOrXSKfUkQfUXR5GIzOVd/zAnZtrW6Tyw8EU=,tag:bJY1hyoUMtWExb7lpocc3Q==,type:str]
  version: 3.13.0
