apiVersion: v1
kind: Secret
metadata:
  name: rustfs-oidc
  namespace: rustfs
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:toXDW1ZB/6nXH6ReuxnOFXlgoMwMx4K28OlOCceMdKYN8BT0t+On/E+MpfEFlPq0EykmBsiGvpEvgCdGy1JM/w==,iv:piaCCEWwStmEB/euabHOV3aOvm+ABwCSZl+a9ps7Rf4=,tag:6jdu6L5MZ8XbFHVDYB7Bqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR0xZYjRpYjFpK2RhMzRZ
        SjhKVUJCYWRkcDJKeEpJVU55SVMwci95TVRvCkVHT2taNkY3RVlVSWJ5dGMzS0ts
        UC9wZmRVVStma2Z1K1dFTWtYZWNicGsKLS0tIHAyc2hSK2NhVkM3UU9Lckg5SlRN
        NzVHV2lJTlM1djN4ZXVjL1lWV2UwWm8Kh9n/mJ+BLD9wkKeziFbvx/TXLTTpGr2N
        AxBqHMC5TcA05XKKev5BsOv20yeM99EWuopzW10IhrXsEo6ZIvo2Lg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRzZKanpDTFVOaU4xaVVs
        cmRyd2xUYXNXd08rSWVHNFpBVFMrOUpoUkQ0Cm5GTVRMNHJjV3JmbER0R2JPcXgz
        RlpTQlMvY0ZodGFNUEhsbXBzNnVUOGcKLS0tIFIrSkNHb0RxdmdqYzYwOFB5U2JS
        YVk4Z1FWNzVLSGlyTWYyaWcvOHpzTVUKERO5wvGUKxgGhRY8+FNH4IMIxap2tyam
        dNkNelMFO5uBFStSHIonigu2HAr+0SIv05Z0V+ClBacbhzeqQUxcyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T20:44:11Z"
  mac: ENC[AES256_GCM,data:OBqSCZirGBOcVvdLsRMfVlqYuT9jJ0hc98Nh+wzVnh6XtKUTmVRvEcrUw8R7Y+cT6abe5XciclRz/G+aQzTrzJoms6x1ONRmTQtJuLvzPzeLziJG4zWY7Z797uq7S0byH36MadbcFi8pNOHtWrsSSnjGt8QUaM6cu1UwDCvbBIY=,iv:oENqJTPmFQfxnX6KIWCX91px05Q4sbx/+EdCmys2Nr4=,tag:ruPGarVZ+svW/5nGb52Hng==,type:str]
  version: 3.13.1
