apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:cOxFTSt1leQWAyCzAAasLjOhjG4qj9buHnRDQOVgFsIapf1p6htZVz33Qtb+Ee0c9yMulDAXOcLiLuBwNduZGiwJW1oY3gWqKap/lcqRjpFXR9mvGvhNJMnAzGEWe8zr2F/gMj60Giq5yNpZMOBXXZ3EdAE72w==,iv:7NbdKxOqiY7EzC70vfkckNxxjMo+kGOZlWDb57mBQHk=,tag:nWR9yySOYeyFS5a9OMebgA==,type:str]
  #ENC[AES256_GCM,data:8QBE/22nkVN8w0m3c1xoG/4l/nucYDSSfD3NFiHRB26IFq8KbRPk2mXpsJmvR1lmN4Jt6731P4JelcV8H6nJePrfPZnKJYseMPIs8ELLbxi+f4lQzQ/m,iv:uH5pr2spcHOG9RydKqv48WsRjd87cP8hNHMLTMO0+cc=,tag:3PQf8SNc3kFQmbrsPUaDkA==,type:comment]
  #ENC[AES256_GCM,data:d1leYDIFRdUpuLSnN1aJ/AazNWmiA074yZ5u/S94SiF79/DejdCmwsf5M6zHuD/rQNvahRhk3RiEa48TAVgLtx8anCOp/CchjR5ydv2k,iv:7f6WmmijbVsfQilWAbsvzzo2U3ozORjf/E8oeJqEZQA=,tag:Mu2J1jg5y5vefqExksPR/w==,type:comment]
  smtp-username: ENC[AES256_GCM,data:BS4K/eyD,iv:oRpo0JteVvIRcD56ygVZdc/U17medsBbOst6sMpKqYQ=,tag:U45hXb+KVyxYQhIJ0maxnA==,type:str]
  smtp-password: ENC[AES256_GCM,data:kwWud8AQeIOaV0lV4JpaIWyZfxnFxw9EUc8HlVMm9X995Hn0,iv:coLmjpe/vQgRtiOtsaOaF8c6CTho3fdVgTCsMlE32nM=,tag:RYZcWXTfXCYrRjB/qnuOvg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVlh6VjVIQk9KTVRhN29Z
        N2pnVnJmSU4weTEyc3ZtVHdzTDgwK0Joc0c0ClJWMFhENUI4dm52V0M1WVdKNEdM
        bm5ONm16T24zeUsrZVZNMmdtdDgralkKLS0tIHEvTlpIZ25nOTArNTM4dDBaMnNz
        UGhhdDFHNk9GRXdSM3ZCb1FvV2loQWsKmdbBetJ1t1rvuWBz+gSHUlel2iC0AFi5
        ON7vizd4dIt+I+TDmxJUts6Nkz6mBHsNklINCQ186tu//V5F5jul0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc21GSWFIanpQZ0UzWFpv
        Y081a1MxOWh2TVM0VllrMTdrNzltMTlTbTFJClQ3U3JkV2F4c3VydWFtRU4rTmJl
        NVFqdmIxZjBuK3NhSG9ENDZMRkpWcE0KLS0tIHhUbi9NR0lreVpDT0NPM1lyUGVT
        L1pST3NkSDJaSkZhVEMzeUdnclhKckEKd8WZqIZ6rRzD+dhZPvjc84LgwULj2q5j
        jWuBlMcPfYGl/k/ayo0Zay5H8bleeWF3J1+UYr/UuCWx01QHRevYfw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T22:36:09Z"
  mac: ENC[AES256_GCM,data:66sRPfqH/Ya4TlOxQ/9j3041EX06bdUfjJh5iVaUtdrsNgv+KOo48FAVI731V7TamFZ6/45NzFvtpXgsEZt08QGw5j9U4iw/YDWIeqcoVtN2jU+ygnWUtG7wS5acU2q2BK8kvLzJi+dd8QhEB6grFzlURWMVxhtxrkAwhwF2xL8=,iv:kRmolM9ig65s3N2nwmMJKfKiLGmn/OPb8fqhiq16dms=,tag:r2gncxI2bbednmhfdEF7Nw==,type:str]
  version: 3.13.3
