apiVersion: v1
kind: Secret
metadata:
  name: random-gif-secrets
  namespace: random-gif
type: Opaque
stringData:
  bot_token: ENC[AES256_GCM,data:uZKDdGESFFaYqXPE6IXV8jMBmTD3apsBS3JnkbzBn999337YnLADeJjWUMkWJDQeSVQmsaZfZkBAxXbcrDA+WjVZpLdbD0cF,iv:Sil/kKomIBKUYZZPbbuNRn1niYM3xEIbA+GpszTk2gM=,tag:U6kSw9nzHH/qpQsHYiUhhQ==,type:str]
  client_id: ENC[AES256_GCM,data:sSgGWagRgQFfJOFBhweT8bvfPQ==,iv:wpk9B1qGHNPC4pi9sPIwOjDzAwhNoa0nYEYI5luOacw=,tag:nZkHSCZ94cFCnYAKckUAlw==,type:str]
  tenor_key: ENC[AES256_GCM,data:jkRv5uY+aV5tygcn+a4t3eDm5713kYnzRgW/mOq7aqLP6a4+76+Z,iv:fXu3KkoeKxPH6Qzpv4/VTFExQXxY0SCdWmOuU7y+gN0=,tag:6+D2SDPwLoxT70TTzw99Ow==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M1Z5OC9oRXFVZTN2TTla
        M3B0M2draEhLbDkrcXNSU2NCQ0RXSHZZMFJJClZ2SlZMMUtrOS83bW1INk9KeUhk
        K285bkhWclhFRmFpZEYwaFJFU29sYkkKLS0tIEVrZUNWL1Z0UCtydUpzYWZTcVU0
        ZzJFSWc0cm5FR1VDam5QODQxR24wUVkKn8Qg+itjAevkBqDlIYrud0UUEHJoIAvd
        UqxRdYPoWD2TSzrYzArBYtq233ckxqckcgxmE5gW/noLtIm1LbzudA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T09:26:27Z"
  mac: ENC[AES256_GCM,data:0lnnb4wfu9c8aJbz1Kf8v0WU4i9Icf7uKQgQFcKv43iSnN85SlLSjB/xbFHnL8kjxnlRLtMwddfl4u29ISEaG0xyJPjhJasJ4rtkAqNhY/F/476XhFNlZDiwjYlxYomO5iEx7QbUtBca65FLkMxO5brV4+DmQaguaDR2xQ6LCK4=,iv:1Y9s8Xc5b/PMNGmJvgHD0eh5sSSHOVYwJSjZ0oplU9c=,tag:lKPdY0jtIKoHV7aJ1ZqIgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
