apiVersion: v1
kind: Secret
metadata:
  name: random-gif-secrets
  namespace: random-gif
type: Opaque
stringData:
  bot_token: ENC[AES256_GCM,data:uZKDdGESFFaYqXPE6IXV8jMBmTD3apsBS3JnkbzBn999337YnLADeJjWUMkWJDQeSVQmsaZfZkBAxXbcrDA+WjVZpLdbD0cF,iv:Sil/kKomIBKUYZZPbbuNRn1niYM3xEIbA+GpszTk2gM=,tag:U6kSw9nzHH/qpQsHYiUhhQ==,type:str]
  client_id: ENC[AES256_GCM,data:sSgGWagRgQFfJOFBhweT8bvfPQ==,iv:wpk9B1qGHNPC4pi9sPIwOjDzAwhNoa0nYEYI5luOacw=,tag:nZkHSCZ94cFCnYAKckUAlw==,type:str]
  klipy_key: ENC[AES256_GCM,data:KgBJw0zgconhWScqwGBKPKtqwc2uOuThtYoUZej+ekj+AWXtkko7U2xPBqWgqkqoedYapJQnPxRHdtsOi6aOqg==,iv:wLU19WurKwRoL5zv7E3Xk0JuYfbrAA/BNR5FIJxR5QI=,tag:dtssArDkP4VtHJM1EQzJiw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M1Z5OC9oRXFVZTN2TTla
        M3B0M2draEhLbDkrcXNSU2NCQ0RXSHZZMFJJClZ2SlZMMUtrOS83bW1INk9KeUhk
        K285bkhWclhFRmFpZEYwaFJFU29sYkkKLS0tIEVrZUNWL1Z0UCtydUpzYWZTcVU0
        ZzJFSWc0cm5FR1VDam5QODQxR24wUVkKn8Qg+itjAevkBqDlIYrud0UUEHJoIAvd
        UqxRdYPoWD2TSzrYzArBYtq233ckxqckcgxmE5gW/noLtIm1LbzudA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T10:18:35Z"
  mac: ENC[AES256_GCM,data:mpOH1lu9kRYs/UXc4l1n8jB+MQeiZ78TKDXVhpN0En/dFgK+ZLo5hAFivq09rUtozbUpJP9jxBik9+PJui9Yjoa2bgcAg2UR8gE6MA78A0JBy2mnhUHuge0L97lwtZJKZ6Jg7rsmG9ef96Qbs5OkiTKQbJNiD5pfN+Et8qJ7FWg=,iv:7DkDacZc8111l6u8oe4VqQ24u2+DuKoV7FlM1Wf0Xq0=,tag:b7icCph4x+rhMu9MOc2ZyA==,type:str]
  version: 3.13.2
