apiVersion: v1
kind: Secret
metadata:
  name: random-gif-secrets
  namespace: random-gif
type: Opaque
stringData:
  bot_token: ENC[AES256_GCM,data:uZKDdGESFFaYqXPE6IXV8jMBmTD3apsBS3JnkbzBn999337YnLADeJjWUMkWJDQeSVQmsaZfZkBAxXbcrDA+WjVZpLdbD0cF,iv:Sil/kKomIBKUYZZPbbuNRn1niYM3xEIbA+GpszTk2gM=,tag:U6kSw9nzHH/qpQsHYiUhhQ==,type:str]
  client_id: ENC[AES256_GCM,data:LM5dVWseY8Q2RKrE7x5mQ5MN4w==,iv:WGQzS/XCqPEePKripayNmaIfyUnY4+UUnd76Eo5eeCQ=,tag:T1bPIsvZCIx+lXwhVr6FDA==,type:int]
  tenor_key: ENC[AES256_GCM,data:jkRv5uY+aV5tygcn+a4t3eDm5713kYnzRgW/mOq7aqLP6a4+76+Z,iv:fXu3KkoeKxPH6Qzpv4/VTFExQXxY0SCdWmOuU7y+gN0=,tag:6+D2SDPwLoxT70TTzw99Ow==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M1Z5OC9oRXFVZTN2TTla
        M3B0M2draEhLbDkrcXNSU2NCQ0RXSHZZMFJJClZ2SlZMMUtrOS83bW1INk9KeUhk
        K285bkhWclhFRmFpZEYwaFJFU29sYkkKLS0tIEVrZUNWL1Z0UCtydUpzYWZTcVU0
        ZzJFSWc0cm5FR1VDam5QODQxR24wUVkKn8Qg+itjAevkBqDlIYrud0UUEHJoIAvd
        UqxRdYPoWD2TSzrYzArBYtq233ckxqckcgxmE5gW/noLtIm1LbzudA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T09:03:56Z"
  mac: ENC[AES256_GCM,data:3ADDIzMmECH2fluWf4L3AFZ9mS8cMNHdnluZR9qAktKnCzk4yot4oJ/X6jNV2BM5AS0kMw1LIpkIxvjS0ZHTCLL/vgExAl7/sA6GSc/ld60a0YJAYrYBNkN5XdoZBXi2LfFOSacqRe2vPwKBDGMn4bEmXGTW/yJSAFPXFRs+aGo=,iv:YrF8d2di1CaReYqAJ20+I11u/sntE+5ULmn9+8dOckg=,tag:Nul1oeNJXP+yJsfKwu+SyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
