---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ca-portal
  namespace: ca-portal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ca-portal-secret-reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: [secrets]
    resourceNames: [mugiwara-ca-secret]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ca-portal-secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ca-portal-secret-reader
subjects:
  - kind: ServiceAccount
    name: ca-portal
    namespace: ca-portal
