apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: umami
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:S16Navt5dtuIc3Hl,iv:No1+INdvulIY8S0YA6STzEf8CPt1CmrBMR2v7Cgwxao=,tag:XA9mFjRnLPAS8YXy93G4+w==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:hz7SCCIQZqO06gwjXPJgRwJZ7Y4tX3Z23hMr/hV+1D2ZT7Ps+CC2yA==,iv:5Ro71x4sQUBwwLWU4VawsG3XnlFCTu93HKwLlIcA8OQ=,tag:jP+JzCOm9aLZBGD6eMBsmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV2ZxRG4yeTNXOEg4M0RM
        MkFjYVJYdGpGNDM4Umd0STh6NmVKbThkWDI0CkFiUTI0S25LU1I3MHVZNVArbVla
        ejVqS1FyWEQxTkV2ZzYxK1B0eUc3ZlkKLS0tIDlEWEJkdjNkVkxIdTg4NlpXV25x
        WmYvQytEa1ZoanVybFJUMVpYNCtiMFEKuIDlyyW3c7Qp+Yn65mba/uGfsArIAOvi
        +onjLlhvuqnyAO42j8ZyvbR03ngrlPjBscxCcO2HaI4k2eKAgEHQHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL1ZRb2tybzM1UGtYTTl2
        WVJnVDE1NzBHcG1SYTRyY0o5NkpmNDU1K2lVCjJsdVJ3SGJKWmNzeDZJc1dXYXZD
        T21nL2FTWDAwanp0andoTDFDcUtGMVEKLS0tIFR5T2hRNTZ0ZnlBOWhONFNWU2hX
        Z2JjK29qZE9IODBpUHlrQVhRQWp6UlUK/wCvK/A0lUrdE6+CYit6V7mXmEUE5OYT
        /wyJr3IC98Jl5Zm/x6OEDrEbHnIAwd//2+hxXZTcFs/WlymkwhX3cg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T15:14:20Z"
  mac: ENC[AES256_GCM,data:pFDBjPj2C8YM+TJFvIvigW72v48eWmBhZgd6MXYatQYjvyo/NJLyBsA1Q9ZIhVZj/zYsoSWiKZWJtwZh0mQorSlGm3a+PA/Tdvetq2m7p3uMAGzWCkmyuSz9aAFaGx6raN1E06k4nUdhcSRpELel1R5rFRDwpQ4gIzFZupDhXP4=,iv:hjN2moFWeLy/UXPBOZl7CC6O4DGz2OPSjfpLwgKDGPk=,tag:cacWMm52uhxHBr4glk+c5Q==,type:str]
  version: 3.13.0
