apiVersion: v1
kind: Secret
metadata:
  name: umami-secrets
  namespace: umami
type: Opaque
stringData:
  app_secret: ENC[AES256_GCM,data:+Qm1iDr9yl86k7VU58SPiZLNrMDggZ3Mff0xS1AIIhSU5zPfdgoqFKTT7KXIE77dqyZnmsir19bAvTS1QEDgeg==,iv:ylfukq0kIXyEN+2AGgwV/Rmf2a2/D/iglLTstmt1clo=,tag:InBpgNPs0Vr7+HEOoOgXVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUVZIR3BNT0Fja3VhMnls
        alY4V2N3WW02VzdpM3RLV1hPV3hxNnZKUTJBCkZ1V3JaNUtZeEF3R0NxT3Nmc05w
        TGs1QlIrR3RWWlhFVXhUdlMrUDRkQzQKLS0tIHVHSWMyVjBVU0YwazV5ODNHUmFW
        QnZQc1VVOFdyd3J6dENZWlFDS0tBWW8Kk40xGSEGWut0UHA+Tpgi2nnpn5V3FiuH
        A/okmWHseT4QivWmWA6u5WTfFKIvtjRhZmX/T7CB2FTZdWjlywS7gw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc0FnOVVlejREUnpmS2Vw
        ZlVBbnFiRU52NDJNSFZpMkxJNGUvY2FrdFRZClhhVll3Q2l4SGRkVUw5R1ovTm5y
        OXFwOFZQVDdtdmJWSU93MGRvZ3F3dEkKLS0tIFJaemNRbEVWZHl0TklpdEl6Yksz
        SGM2VnhVQTlIdVM3UXJnd3RzNytudkkK7r53NRk12+yAmjwMC/EzhY05MD+kDkob
        lpw46A9Qw7lfZnW/8AvVWL74Zp0KtudebmdOVETfFtaZQKy0ZQ4rmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-30T13:23:02Z"
  mac: ENC[AES256_GCM,data:EIr9Tn31VSC5K4cDwvge1QoetOQzP0L+ektjOhye2X4weZjkJtI4GRe/rdgPGK5vNps3wmF77lp842edAeHATi9vNk0MBP+BlaYVo0dtdPcwWkKbTBKHOAosZFhSGBA5e6k6qOrX+IoXXB43GPQK5SaVpe0mQ+0BtUgEkCYZu9c=,iv:pMlx4ZTiHrd24Z5/ktlc3FowiTdyVfgZRE2RsRuMgBQ=,tag:qnRmjJJHqatkK+VkXMk7bg==,type:str]
  version: 3.12.2
