apiVersion: v1
kind: Secret
metadata:
  name: umami-secrets
  namespace: umami
type: Opaque
stringData:
  app_secret: ENC[AES256_GCM,data:+Qm1iDr9yl86k7VU58SPiZLNrMDggZ3Mff0xS1AIIhSU5zPfdgoqFKTT7KXIE77dqyZnmsir19bAvTS1QEDgeg==,iv:ylfukq0kIXyEN+2AGgwV/Rmf2a2/D/iglLTstmt1clo=,tag:InBpgNPs0Vr7+HEOoOgXVw==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL2RSSWpURFgvSncrY1ZM
        ajI0d2t4WXAwaVQ1a0VBci9sd1F4OTYwK1RvCm55RTMvbFBNU1FIdThENHkrQzZz
        SFpTU3pkd28yRWxkVDJPYklRMmJKR0EKLS0tIEhMZTJxNklGNSs5WGxHazVETE03
        dEh6S0VReHRreEkvY09SYks3aU1hVmMKumOlx2vhS7IEIGbCHULd9fv54ypgYLiY
        8wwrK02KqFnfigLliyjUnUIe88/puBzgPc/Iu2P1TYtbG59L3DS7uQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T13:23:02Z"
  mac: ENC[AES256_GCM,data:EIr9Tn31VSC5K4cDwvge1QoetOQzP0L+ektjOhye2X4weZjkJtI4GRe/rdgPGK5vNps3wmF77lp842edAeHATi9vNk0MBP+BlaYVo0dtdPcwWkKbTBKHOAosZFhSGBA5e6k6qOrX+IoXXB43GPQK5SaVpe0mQ+0BtUgEkCYZu9c=,iv:pMlx4ZTiHrd24Z5/ktlc3FowiTdyVfgZRE2RsRuMgBQ=,tag:qnRmjJJHqatkK+VkXMk7bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
