apiVersion: v1
kind: Secret
metadata:
  name: homarr-secrets
  namespace: homarr
type: Opaque
stringData:
  SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:TWAlqu10H90E3tGdf8o7rgTDyt3KEkWnLC8DBAc1k7pcsZKNx1eIY1vm+nOBF2o+x34nbb5yYCmYiRnIeHi5Pg==,iv:bmYHYkTYFkGUXmyeJCuDJJlHr3QyRv4/J8xLvcGz1KY=,tag:GoQCaupey8RdV3mn/reOQA==,type:str]
  AUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:th9IFvX/mh9uilo9P2gmI6upIIR6loNlEG4oXXvhCzS3Sf1iDrVPIpT/frf4J0q7yhmenuDeCSP8jGTsufvfTQ==,iv:3OsYpYzMURkCVM+CinieF+Z8sQ3GFL6ALN7MAKWPPC4=,tag:fXZDvCFBir2OfkZC4Qo7wA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dk9QUXZsUWcwZkpSbkxt
        ME4zNWlsZDhxVENBRy8wWTA5UkdSSEk0MVZnCmR4d0dtaEpXNkpncDI5cmpXc2ND
        b1YwZnhRUmpxUjNSdDZUMktDTWJrMGMKLS0tIERDUGpPamZjNlpGTVk5WHBtUkI2
        c2tBV0lLZ2FEUmdENXlnZEFuZ09IdDQK73FevDxbMavDYerflrpMYX/NXaSlEAMT
        p2YZQ+T4FzeCwE96RdEWhvmpl9xN5jNKaAUFI6nC9qxnzP7eHAza8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQkxVeDVQdUNqSm04UlFZ
        OGJWS3pUaml3Mm5oMk9zcHR5SDd2Tk92VDFZCk11eTZCbm0zbGNZQ0RpQ0NZOFFm
        VmdYRDc4Ly9WdnYzUUVtZkhZd2dWVXMKLS0tIENZUTFLSkttSEJYbkdUdEtwR2FF
        dUwrSytZbGRUM0dWNzlERy9oM0NLR3MK7xXgTu4Z+qx0bg0p8kNhG/fQwOFIw30u
        aCUPU0FdlxnZWrFEJoc4yIuj/t5xedThkP+d5uXSBr0ftSYCFY6eNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-15T23:21:41Z"
  mac: ENC[AES256_GCM,data:wOQZxdI7YJWstg2VIJLnebQr9qTtjfRIExEDnoreiquvt/QSRwS+JgQbSsBELS7f38m7JPDRFh4/C9rDr+YtZch9xyvwtE1yyiqNFv49o4BI3YAHaBbtks+MwskIZf0eBdHHSzSSv6VzhV6alhA63/OXLn9x+APzTA1AK5Sds9w=,iv:upzJclUfgQergMHTJKcmhPRXXH+vQpdB8yUHpVFGuiY=,tag:ajQZUj6GuXqjyYyZ+qxusw==,type:str]
  version: 3.11.0
