apiVersion: autokuma.bigboot.dev/v1
kind: KumaEntity
metadata:
  name: homarr
  namespace: homarr
spec:
  config:
    type: http
    name: Homarr
    url: https://homarr.${CLUSTER_DOMAIN}
    interval: 60
    ignore_tls: true
    accepted_statuscodes:
      - "200-299"
      - "300-399"
      - "400-499"
    notification_name_list:
      - discord
