apiVersion: v1
kind: Secret
metadata:
  name: valkey-auth
  namespace: homarr
type: Opaque
stringData:
  default: ENC[AES256_GCM,data:+PHaBVbPj/reCJAfKH+Pt3hcOWnpmlBoe2AKNUc+AXrskkQxqtZluvBc,iv:ndxygmakreyXtp0AE6/6xvS2IGvgIvRTviOpXnnZLrs=,tag:2uZMl1cJL4EIMK4toqDIIA==,type:str]
  password: ENC[AES256_GCM,data:UehzORLQyCA+F8uqIvbYpl7wstQpTDriyg2hYL9dwzBHL3HfiWTxBVPa,iv:pW8G354jzwNgYNCV63LTVMkjki45+Az2mHwkIJwm2Ug=,tag:1SiH0f4UXTulx0JwwATf6w==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUVJ5bUthenBVYmJDbDVw
        eVp5b0dWNjFJSEdWb3NRd0JnUUh1ZkNSM0YwCkl4aDlaOEtRRE94TnJlbFgzNmVm
        bjQwM2E2RWF4VTVRL3d1OGR2SXBwdE0KLS0tIExvTUlJQmxhSWZFV3JqZkdSdGRV
        TGVBdy9XNXVHYVZkWVRFUDZEb25YeVkK3iLkv4E4oxnykX32/Fww6ARZIPyOBPBR
        0gbpzpdKDyfrLMM5cDaRQPmm5SwzWgFP5xRzycJ+ySpbQyz00DGYIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T18:10:28Z"
  mac: ENC[AES256_GCM,data:Xr3WryNerJP+ib/zzQlaVj/KYe3XHJ4R88roubseZMcdtLXnbIZFQI8W4mqU0p2M4YhV3adubUevMAZQccntvyZ3TzPo0z1ZmdyWBjbhkXymT1M/aw2h1AuQNFf5fz59og80wUqAKROGr0fhyIJogmm6Bb8+liLUWDTxwID7ddA=,iv:GVnFpCEZdHirTj0Q0RFuTT1zUV0xp/vQvyQKmc+boBQ=,tag:6b5f1+kQ24va5CJPb1Ie8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
