apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik
  namespace: authentik
  annotations:
    external-dns.alpha.kubernetes.io/target: ${CF_TUNNEL_HOSTNAME}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  parentRefs:
    - name: internal-gateway
      namespace: kube-system
      sectionName: https-auth
    - name: internal-gateway
      namespace: kube-system
      sectionName: https-merry-wildcard
    - name: external-gateway
      namespace: kube-system
      sectionName: https-auth
  hostnames:
    - auth.${CLUSTER_DOMAIN}
    - auth.${PUBLIC_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /outpost.goauthentik.io/
      backendRefs:
        - name: authentik-server
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: authentik-server
          port: 80
