apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  instances: 3
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie

  storage:
    storageClass: ${DEFAULT_STORAGE_CLASS}
    size: 40Gi

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      max_slot_wal_keep_size: "2GB"

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-credentials

  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-backups

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1Gi
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-backups
  namespace: authentik
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://cnpg-authentik/
    endpointURL: http://rustfs.rustfs.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: rustfs-s3-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-s3-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-postgres-daily
  namespace: authentik
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: authentik-postgres
