apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: authentik
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:GcJDUHE2O2ya05nS,iv:270l8qZJIc5YP6PJ786kE17vbjWG/IRWq85jPjJJv7E=,tag:dJ8/kMEqMTM3o3z7wNYLLg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:7ckC+wyQHetFMpfyMmtpd6YNFgNbPmJxX2pdl4aeS7TweV6PhN7MMA==,iv:ToSRCB6KBmJRgzDvqM8wUM/HhSaiaA7iq1UBKAGa0Ns=,tag:xKBXRQ1/F+GRSVdApiUubA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN0lodnBSdERtY2tVSnFw
        aWsyRTdZQTBkRTlla3MvWFRUUEREZzU1eGg4Ck1hM0R0T1ZRTXdhb05CU1ppcTBZ
        RUJzVVVmZ3liSVFJME5NYnZlYlhrSGsKLS0tIDdGU3VtVWQ4K0pxVjJWeFFiZkJP
        TXVGZmRPaHByRklVakZNendjendUU0kK9LFC6xU6CqPWJCCO+Uz/9sULnK7KiVkV
        vcPXU9tFuKoiDQrqNLNkRXtxmLLclZXqWJx7iTeP0EadIB9b8TQDaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T13:48:13Z"
  mac: ENC[AES256_GCM,data:KhNChVzbQDq1RsVnIrgzOAsnFHSkn3hM4JPZuHoWpyvK1PHwwaiAj9azLdbqUklFSoBZX/oC4I3DY7U6fdO1Z/DKdx6IF3UtDDUyaFYjPS0hddKHnoSeEkfLdY/f1X8Sqdvss18ur4x/Bv6icL50/Ee1U0Qogk3fdPd42Y6JHkw=,iv:0qJ0a64IHfDrADGzDaaDzpfBoEKGVk5EzihtF2iFfNU=,tag:D4V0xS84G8GSXzUnh9Q+vQ==,type:str]
  version: 3.13.0
