apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: authentik
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:GcJDUHE2O2ya05nS,iv:270l8qZJIc5YP6PJ786kE17vbjWG/IRWq85jPjJJv7E=,tag:dJ8/kMEqMTM3o3z7wNYLLg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:7ckC+wyQHetFMpfyMmtpd6YNFgNbPmJxX2pdl4aeS7TweV6PhN7MMA==,iv:ToSRCB6KBmJRgzDvqM8wUM/HhSaiaA7iq1UBKAGa0Ns=,tag:xKBXRQ1/F+GRSVdApiUubA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYzhTejZMUGw1Nmc5ZEhq
        UHlSaFRoNnQvVFRwaU5UNDlCQXhvN2ljcXhrCmRFdlpFcThUTlFuaXE0bU4zL0ZY
        OGQ4ZkFnaEw0S2QzdE94eElnQWpLencKLS0tIG5XM1Q5L1d1TzdFZllVVHAzR1pr
        UndVZmpxeEFxdVNnQU1qTzh5L3piSUEKFufb3B/cXUkHjFjgxwuRhopPLUxvP6H9
        H6zzKIoGq/NA5XYBJgGBWV2H8BAjbbjAYvs9JjU2cyKxxEMqSdN7/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWEp0M0VYOFVUeXQ4NFNy
        SWo0WnhIUEhUYlM4MGF3VXNkdFoxZFhtNTIwCnl4UGtQa1J2blZWdU9ka3pOR25M
        aVppR3BZUWtrRm5uL1dFdmwrRjM5SWMKLS0tIHZqb2ZhWUtBWG1EeXJ2RC9NZUlw
        eEVCN0dQdzB5S0ZnUjBYODh0enNJNUkKPuLKoBrx0w8nZzRSDHvw2Mmf1F2NM1/y
        V+vKL2Ty+vCkD82Lm9aH/QRTpPOdpcNrIrau6NcqE8yLrytZ61yLzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T13:48:13Z"
  mac: ENC[AES256_GCM,data:KhNChVzbQDq1RsVnIrgzOAsnFHSkn3hM4JPZuHoWpyvK1PHwwaiAj9azLdbqUklFSoBZX/oC4I3DY7U6fdO1Z/DKdx6IF3UtDDUyaFYjPS0hddKHnoSeEkfLdY/f1X8Sqdvss18ur4x/Bv6icL50/Ee1U0Qogk3fdPd42Y6JHkw=,iv:0qJ0a64IHfDrADGzDaaDzpfBoEKGVk5EzihtF2iFfNU=,tag:D4V0xS84G8GSXzUnh9Q+vQ==,type:str]
  version: 3.13.0
