apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:RXrbAC3x1Y+i,iv:7zewWMCKD9vseLc9umGIyDX9FwKFtwJLBxHXuO3NzkQ=,tag:/3GvkYWilAJmUbXr44lWtQ==,type:str]
  password: ENC[AES256_GCM,data:NcFJoB1E0DSJRYqqSZ/4a8eJF0xZCPQwzLc3Nou/sJEqF5IphJDI9btauF4=,iv:k2bjRdYVoTwNyPJExOrz+o+Etu9UsNHj1LTXyDPEUrc=,tag:tsYCxJ8OAK3YQlIdTzCQKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N3dPRjNOV3hleDlyMUdG
        a1VBTDFWOWM1WXkyeXZiZ081TzJXUkRjd1dzCnZib3I4UEZNZzdZLzdhY2VFMDF2
        RXpHOUNYQVcrOUpabGFhaWNvVHNBNm8KLS0tIExEczZSWFdDajhPc2YvS3g1NlNC
        ZnROMWhqTS9ER3NJYjVQcTNkdmtMMncKvooAqT/2oddrZNozton+XApi6WrHpn9L
        yq38WWbvmNaI0txWSRwxpI+cNx3sID4UBGq6DwB4ucYnVfL6dlT4Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T17:02:12Z"
  mac: ENC[AES256_GCM,data:Cw4feGebLwIBOC/fntKDGNCNP4oL6gzwDmBtNgLTn1Z0bngsIhhlzSZvNwIg2MVaHCImfp3VqchYvxi+BVG+QSU4auV3yVRMVeomahAQBbJJdALUFjqoXiwRGL8dCriUpeN8S7jjK0KOOo9zhHqzoWVcNCyYOFCx/0PNyM3LBpE=,iv:h+QUZ4dSKoI72vjLxTgPPsvxtSSRHpFz7WxfmkJGHxg=,tag:LsShysYHnkd1dVffPUlNyw==,type:str]
  version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
stringData:
  secret_key: ENC[AES256_GCM,data:KHAVqAhYNhT6sCyA7XfsRN3JfJQl6QM1WqDQy/d7u1MhAAO9yC2pH7zBWX/kQlSv7/uwiJ3gSC1nWkV/8oQT9g==,iv:OUKfwlhKxtzHEun9kM72Z4VgVcudLIJGmEbMoslADsk=,tag:S1Dni5mL5kRY52W4p27XKA==,type:str]
  grafana_client_secret: ENC[AES256_GCM,data:05pINGipiaJqapOYeswvHeTorKkqKTmb9FvvmIMWacA=,iv:bWo/nvuMobTl2qUlEzUhI7pq+ArXu/fwDTzvr9bGS0A=,tag:gHR478HyP2JFR2Rn9bt+lg==,type:str]
  ha_client_secret: ENC[AES256_GCM,data:Pd+E9Z6xPvVeyv7+7l7p6x7Ff0evYx6bsZwStAD7F/ZIHxMiaDshWPQmPA==,iv:eFISuibofBY6sDbSHHBzqGUBhafv7DqMz8qZM1sUKcc=,tag:wB7DvYN7sf3XrOOuE1o9dQ==,type:str]
  homarr_client_secret: ENC[AES256_GCM,data:wN4FGRP0DaFQIQiRpksdy6Hrs5cwlcHqgm16qwWevKH0vHm53OoSD/UjHZFxWnjY0YPwrNlPpWrADF/GXHy5vQ==,iv:0LFpgCBDs3d/Lh9oIMCpMxocc+frHVMbWQffGuC6aFY=,tag:wz9AUC4id1KtK1cnUUPCoQ==,type:str]
  immich_client_secret: ENC[AES256_GCM,data:Q2lo+iiHAO+LJN9ZNl7TD61RpGSKpbTm9HkkonUxRcfJrdgObCWgVRiAWASY1/VYxga/xFsyfOpgWKMgRCsizQ==,iv:P1X3RvWDH/QQYO6Teg8UOO/EH3CYftEGaBjl0//SgSE=,tag:A1tzINorEWak4Cgunf1kwQ==,type:str]
  cloudflare_access_client_secret: ENC[AES256_GCM,data:Xd2pBl62JnA1CmmA2WPIQV9emFOVzkzLCOKBKMVT8zTYSi/yGa0Hw0ddXFcUy/P1IObAv/ZrN6/XgrDkbz/wwA==,iv:ZOSaM2BCU7FAJqxAHHfvBi7dHjXVtP4AjSI5slseYGA=,tag:2M7Vq+YLOEu4r/kQZOo5yA==,type:str]
  rustfs_client_secret: ENC[AES256_GCM,data:borlLR7Y4i6ZjQ2veEwp8cGqNKQK/geWrzhdNazxXEEZa5w4iQJ6t/7ydssP/DzlwgdZhNiwP88cnaXzSZudRg==,iv:WwO+DKet1Pgiq4k5V+wzkSpUOUoZXh2t25YzxDJLvgI=,tag:9F55YJM1ygIBmcslvfF8ZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N3dPRjNOV3hleDlyMUdG
        a1VBTDFWOWM1WXkyeXZiZ081TzJXUkRjd1dzCnZib3I4UEZNZzdZLzdhY2VFMDF2
        RXpHOUNYQVcrOUpabGFhaWNvVHNBNm8KLS0tIExEczZSWFdDajhPc2YvS3g1NlNC
        ZnROMWhqTS9ER3NJYjVQcTNkdmtMMncKvooAqT/2oddrZNozton+XApi6WrHpn9L
        yq38WWbvmNaI0txWSRwxpI+cNx3sID4UBGq6DwB4ucYnVfL6dlT4Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T17:02:12Z"
  mac: ENC[AES256_GCM,data:Cw4feGebLwIBOC/fntKDGNCNP4oL6gzwDmBtNgLTn1Z0bngsIhhlzSZvNwIg2MVaHCImfp3VqchYvxi+BVG+QSU4auV3yVRMVeomahAQBbJJdALUFjqoXiwRGL8dCriUpeN8S7jjK0KOOo9zhHqzoWVcNCyYOFCx/0PNyM3LBpE=,iv:h+QUZ4dSKoI72vjLxTgPPsvxtSSRHpFz7WxfmkJGHxg=,tag:LsShysYHnkd1dVffPUlNyw==,type:str]
  version: 3.13.0
