apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:pFwSZBQV7m7w,iv:MejmIbkhKUqwrDJO12uY/bHXeCPwjotZOnKEhRz9cpg=,tag:ysbdrOTN2pn+9UrRjdn49A==,type:str]
  password: ENC[AES256_GCM,data:NOoAkkcOBkMDty7w8v9HNlhzG4i8gn/LFWF5rGRB21a6HaNRomdNX2ykg1o=,iv:MEzjoGFq/pVOb/0JuBt0BtpCj94k7jL4vZYsEP3aQ14=,tag:3mOJOw1EFkHi2iT3wseK4A==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ1FwTHFFNmhUWENDanRJ
        T2FiOEt2TWEyY1JVVndOSmZ2OEZjaExsM2xRCkRiUXNLeHlZd20wRFZTU0g1R043
        cVZyN2hFRjN2VmI1UmlwWjZINXFPRDQKLS0tIDNEb2lMa3MvUSs4anQrVDdHOXJx
        b3psQ1M5MVRFbEpHbDRobGY4QkIvVjgKCtFQ12XMNxB+A5GsBtkyk+IwmfORJlQK
        9V8IRoH9myVE+xZeDebZxI410E8jUFGC5u7NBXSrxNTZWg3MMrUUhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T17:24:39Z"
  mac: ENC[AES256_GCM,data:uLi6xwSU7tQ9EA8pD+Tq8+oD7j9QBe/pk48MNxRe0BxFET6loj+8btJxfC5QBiNVQl9E8lYkJ41pLrkBjN3Ky1dpMCUEGlwzQXk9oK02eCpAjrBVYJ2OVOGBjHQrjquNbPng3YBtjKiBii1C1Kxfx5Jm8XN1YS1A1bxRRoLcF6Y=,iv:uMHTWGR2zfn1MvUstqKMvSeasbpQ59AO4KwSSMmtjqk=,tag:lR9g6Kz7P8XS9j6+8cI28A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
stringData:
  secret_key: ENC[AES256_GCM,data:8vlCOPVgv3yTVWVgHguwIxyqSI+ghOn+93T5aQOux8bRpVF+b8Sia/QtIYIkbBhkEiHOzn6z7edPkQxTbnJ9xg==,iv:szVhAnOHW9bC/Eugq3lEqjSJzNgQel9MwZD91+hfWw8=,tag:SdNw0HXDZG1ASZr8HALeYQ==,type:str]
  grafana_client_secret: ENC[AES256_GCM,data:o0rEnmSFzZVtlQBm/dJ0CKvGFc75J+/P0KDAiH5YKzs=,iv:c2gTelw+d9E1RUNqBfNyfhPc9OkDxkqYPiWrCIV+/yI=,tag:sSXK7ZzuoDvjGfPXDJ0pYA==,type:str]
  ha_client_secret: ENC[AES256_GCM,data:ybIeXcIu4ro45enMnxamqubku3OwMIVstoUmnX+y27ERY11g4R+tMtQXig==,iv:obpe1sG7s6YXyLj2jRVJOFfi0o0TG/ArPEQBtZgJXRM=,tag:r9J+T5gSn+jbAOp8pF/3rQ==,type:str]
  homarr_client_secret: ENC[AES256_GCM,data:FhL+IQsO1acWmjrnc4mw458a0wu3YYB2HP6mUsudd1nZAUhU58lMIj39HNUgYz+87grFjM4pqXeBrRKcQfZieA==,iv:eXBNB3a187j7qqrpwqJmcNUNC8VsO9FSlz2GkuEaB6k=,tag:Wn4gzfXserDVYfqUaTrrZg==,type:str]
  immich_client_secret: ENC[AES256_GCM,data:1FbbK4GRP/kBuKcl46GpdVJJ8j8IPh4Vv3LJrXDOYkb+RSrjRPtCliS1g8/CKgX3nsnaQ7UYYbjZJjAktzc4RQ==,iv:uK2iCcvyLt1yiEW1tgJUgPsJS2/HMYml6Hs81oQfWmE=,tag:sfd5g95Mx6H0OEFKD7pwZw==,type:str]
  cloudflare_access_client_secret: ENC[AES256_GCM,data:tMbPKiH35ZBXfCo347IP1okGQDw0ZNO9UiRWbU6axz0yqbkDx76b7O8fI45RLw1XyAwU7sq6awM6ljdJj49nFA==,iv:uec/O/aPNAY8mCo9IcASUcwer7kjXKpw4s4VsW7mRkI=,tag:NEaTlx7tLKkSIcwpPswLJQ==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ1FwTHFFNmhUWENDanRJ
        T2FiOEt2TWEyY1JVVndOSmZ2OEZjaExsM2xRCkRiUXNLeHlZd20wRFZTU0g1R043
        cVZyN2hFRjN2VmI1UmlwWjZINXFPRDQKLS0tIDNEb2lMa3MvUSs4anQrVDdHOXJx
        b3psQ1M5MVRFbEpHbDRobGY4QkIvVjgKCtFQ12XMNxB+A5GsBtkyk+IwmfORJlQK
        9V8IRoH9myVE+xZeDebZxI410E8jUFGC5u7NBXSrxNTZWg3MMrUUhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T17:24:39Z"
  mac: ENC[AES256_GCM,data:uLi6xwSU7tQ9EA8pD+Tq8+oD7j9QBe/pk48MNxRe0BxFET6loj+8btJxfC5QBiNVQl9E8lYkJ41pLrkBjN3Ky1dpMCUEGlwzQXk9oK02eCpAjrBVYJ2OVOGBjHQrjquNbPng3YBtjKiBii1C1Kxfx5Jm8XN1YS1A1bxRRoLcF6Y=,iv:uMHTWGR2zfn1MvUstqKMvSeasbpQ59AO4KwSSMmtjqk=,tag:lR9g6Kz7P8XS9j6+8cI28A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
