apiVersion: v1
kind: Secret
metadata:
  name: zot-pull
  namespace: matrix
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:VqglFTXPvAdQAOLYyns2iP1EHd3wd3YW6pPr/v/PKbi3ZxeCJfj+oqiG7yl29kfDhA3WlEWc2a7fzR2qrwq7CYaZuJsiGsEWVYboztgcsp1eRbgKunjQrQ9gnK2tKc1Jx9x7ZjkEVxOoUEE/Up/rvSnEJXU9IUW0rnL/3bAWRd/TQWL8KXuCnc5HyjYhEtms4y3XCe9MShrJcpUX0BYEZSRSgrQ8re/H+/Z08dJ8CFTJkHyCqfJcKs5lWdhySwely1d1MTl9B67d3WjcWORODVSAEecPQb/e0UzLl10SBdqeNgWOZQf7rXdlyDMXvdiSZ/Y4ocCLeACmmPIit4IVLh2tCwdT2IrBQw0fpmXlG13bl71f1vbdJZ4tDRd/2jFhCLgS36GGrIxfwpvcvtXpzcj1seh+m6lUiE283NfKAlzQU0McrB6J/xQdQ6DOL51dKTM=,iv:XLTh7j9v6kJUM+ls3usC+1Ai7GXQWyOGsxDlZxamkVc=,tag:J5Oq36trvIjjhb2sFwNfew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERm10NHlnWlpjbko1SWJm
        dW1nVllMQndqOXpNNTFYZXZDQStPUXpPREdJCkZscGh0TTJJeGxWb2xTZEFGdkl6
        Wnk0cXQ0bmRUUHYrNnpDcU53NWJrZ1UKLS0tIHRmSmRuZ0ZnVTdSL05hcnJMSmIr
        ZUpaUjErODZDT1c3Qlk0T2VBZ2VoNFUKB+ndMTGk3w/dv3lPzEjYWjr0ewL57QqK
        2pF7gFb/PRO28ajPxlcLWwWO/EzaKfLRi8L16/iWl5ctAl+agXkmzQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a1lvcEpHSzVSdG1Na0ZC
        Nm9jTmQyMGlZeEVQdEdwZVBMMjQreGV5RTBZCmcyOU53TE1SWm91MFNTQlhINE5x
        d3dFL05PMkZaRlFKR25qS0VrRVBaN28KLS0tIGM0WkdsWHg3RXg1VjkxQW1rMTRX
        ZGNxQlRtb3RIMkJ1OW1PdzV4TW9Xd2sKZoawaCDLN8n1NqSImi1OUxLIVXZLb3Wg
        YO8+2QNaFrWSXxp/bhgNmzwapbjff2Liq41AFVROGhOI784abGIiDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T14:19:49Z"
  mac: ENC[AES256_GCM,data:0z+b4SyUh/AvGvh63BHHq68OncIIHjkGEadK+91ivp866fwO4sFnjUq49Jfoz4zZmAXBdFm4m2GM7wUTgWCSXrvbgS1tgwtGB26+7VpnZEdqnQm3zsLBqICch9hLX/kWlXxBucvvl7yoYuNwbfvzOuts3Nzh3f5396Su0Sn3t/I=,iv:fuyo7ETrFOyAnzSSK93AY+dBciMy6Bjth0zGDI/HadY=,tag:4aH/KnOpTVroyxE2plxbIA==,type:str]
  version: 3.13.3
