apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials-file
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:P14DCyVeGt8w2fNMLVzTgif9FeR3kChMRzE4sT+iJGh8pB+BW1cSWhZMbgriOlYPx6SqMeMtudD+gV3wG6PIQ/ljGCgxSG+linGiDerPIL9LdOFSw1IufhxPQMhCW7FdggkNFztWouVYeXBxhewe5r0s+oA4VFjr/8GAbIebjGAwWMfndJ1EyFTEVuyqcMv+9zMFOqjNgPHDyV/PEIkqVxaWyxqh02foRKemcHYQ+VuL15o=,iv:pXpY7sDrr18TG8NgTb77JJYuaKZ6ZdYojWxf6VcqioU=,tag:Kx6O7CJ3+H6OsFTexvgxzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNERMeDArR2ZZak02SzNE
        amI0NTNaN0NCWVdwaDhDVDJ1SVZLUCtIdXhZCjBGTlVpbTkxa04vVFNOWk5TUkdC
        RlpOVTk3RVUxblZQQm82eERzSi96alEKLS0tIDZnSjE1N1g2aStCOGVZOE5TeTdj
        U0E2UFNaOHYrY1dia1EvVEUwL255VzAKtPgoXAZ+YvWfAk9i8lmN5JeDfXcQltep
        4rUR3IaFA1WBMUZ4yiN8UmXVny7tbYkLoWm/Na15AG9omso0X/zyKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T09:35:54Z"
  mac: ENC[AES256_GCM,data:DZ/xa0H3wPXJpJ02OBtsQLi3ruA050VWFQcaLMnLOcNjBq8IJpY7e1w33/G3bllsf7AhDnvrc06HJHhDj8xrmSevXO0bZ3PHLUoHRfob+qxiMx+4snfzIWN+dWapKqcpkvyyJjVR+J7Rzqi881f0yeRz+xLdZBXY70K4HekyPFQ=,iv:UOB9iOJbdBbCvIkFHvLqqqj52RAvT8rmk5ShDnb38GA=,tag:++4FQN29cAbY/n5uXkPwJA==,type:str]
  version: 3.13.0
