apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials-file
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:FkFIl+8+id5dkJSHjNfIBfQ4/Nt4Tv3JHDIkNNV7LRVsOnb2beRP4imcczcNikE4C+g3D4+YVYWaWFebgN/TPjpkRqm16lRIvRkDRv6N1nfQVJki49yaDP01/adLd7apGuq/DMYxv8lrwU0Av9dNfhDroD36X8V47GB4OseJ7ND/rMiKJNHT+5IXQgAv1FEEtIMm4QFAFM0K+KkRsl4m3QIdS6kuElsIZCPuA0ZNzA==,iv:b10vzu3YImf1AEpZZseH5UaIeir7zu1n6rL6fDYlyIc=,tag:EhLO8+BDUdOle4CXkqTr6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcUxyS3lzM2d4WU5RK25G
        WExCUlpmcENFUnowak5rbWFBVzFINm1FcDJvClZHd1ZlaWNyREEzcFlUeWw1M3dB
        K0d0NDNCQVBhV3pLQWVpY3YyYUErQ1EKLS0tIFMwOGptbnJhK2xZcTJqZExnMlNC
        N2gxVGZreWN2NTQxV3RxOEx3TlAvZFUKswMrCnWWkKJTREOR08ADctYf2yBFj+Hm
        JdUTb8URlmBSOHntBrftZvKQoPc+pUvXxV+Hn2NsShgsU7kpXMdNCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T10:36:00Z"
  mac: ENC[AES256_GCM,data:HBZmsw002np9nQ50CJWiMR9wAPR1ibTLJ+VaQqr/4iLCAYlQb/OjD9SGSJpba4+b1Ba+tzZDcEsnxnQ1S3tRxn1GaF8cSUXCkldGmwpl1slyVZ0uQpislESd+eqYHF228ImDlZQpXOh+1muJMhrNt0hb2v/nQXgirqdqzwGm05U=,iv:pVEC6vaKuM5unu2+z/TJxvw/0AVFWTfcNhoTjSGQMC0=,tag:N/bY7lEO/uSIl181kBNIcg==,type:str]
  version: 3.13.0
