apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KAMMgQ6ejV96SPCt/ipFvmnhhjqcI2lW/9KpXE+YwTJLya6dWvfsyU5OLUk0TwwMazPzrt9v6SqG1LfIsdVrvfywaDIWbIuP/sihjwfARZym8JlHuHatqgx32M1E3FGUVKkDlG6zRYLEvbm+x3xHu3lxuTrJ2vQxnRTQJOkTcoaq3wakYFfZSG+QRGvAchuIveUnLJ1jTiCzGydgLhvKJ+zgTSb7eOYJWD8kLe1MMWBvEaGKQIUXGw==,iv:v27ypv5s8s6qWn/djjaRQ0Fpd8Tc/ek84SWrZqUAIV4=,tag:oCBvEI7yJJPIKRXqHOPWZw==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTHpOenFhNHdFNWpkcUdW
        NzdFQVNZbzd2YkdvaWc5SFRicXFnakp2OEZnClRlc29OTkE0emFvWWxGOVdIVXBU
        NWlYb05yQnM0WjlqUm5KOW1NM0FLcjQKLS0tIGhOMHJFWGtRSnlkemk4OGdGQTh1
        UitwZ0JCUU1Sd0V6V2VCSWdpcFlvVEUKa8TxyjN2ZWkVBr5puxKXyuh6nKI98q2z
        0dTwOSNeWccn2vqLfmSqIX+DpINhezmu8uxyoLjCUqCGcqjTSKVt1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T20:18:53Z"
  mac: ENC[AES256_GCM,data:2AKf4ugjuE0qublgU4Li9kZTjsR1pkm6EK5rxc0kuXfpHaspu0pGHQtOu4lkr/6bLurLdo2jWKxpb6HXOfIV+bmNeOrjw6Z9n4X66PoXhJrbosZunM0XcMPP5780elrWCLyWLjdKfCeyW3hYOrR26HF7Hk821Y8rGweUm7wFhz0=,iv:ELu+PfWvurG3+hssAb3nhaJAbet1h64Ef81RfNim3b4=,tag:LbxeX6y7wv25DCc73FQ6PQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
