apiVersion: v1
kind: Secret
metadata:
  name: dozerdb-secrets
  namespace: dozerdb
type: Opaque
stringData:
  NEO4J_AUTH: ENC[AES256_GCM,data:iZ/n33KxcOUWRTleiNlYVVW0N9MLRwmw7GAy/D0itDT+iIyYK7cGQjq7xcHfDaeKKXw+Jntp,iv:8XAK+Ut3ezeUJKJmj177dpnEMtw3RNNm2GlEcSJv1Hs=,tag:MtiBoyoWmleTbZZRvC+YRA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWE5VVjNvZzNaazBGSHpj
        MEswUTdQaHRnTTE0Q2ZFOFY5M014U0JMVWtvClJxREVWUDBMb0lNNThsWTR6M1VT
        ek56cFQyS3F4UGF5RGM1MlBPMktuTkUKLS0tIDFBVzNhL3ZTOCtTWVAvY3d5bGt6
        cmRPR3JHZDBsaFlScWxobHIwTmc0dVEKzNk1r6ZcMCqrV6GZ6HPt4zEzUoqiXbug
        7tvpdvoWQgtG+SyU56VVPnEvfU0/T4UZPKa5o1Nqfz4h5HwLEJPNzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T12:52:48Z"
  mac: ENC[AES256_GCM,data:hxzQ48lHmM0OFUhUF2ub5n8GzC2RQGrMkyzl7B/lOd1dKERFjqURIEGVLW7zWsDs/3dTCCWknqDIAeP/f39fPGDCTvBRELPLYwoFwjIHzF8LVY+ku/9y8/aw03NI4px5IWHF1os17jmaCAs1Djg5AkykbXsk4dCVbx3HbtglcKM=,iv:mbVYq3vQ8SGPZ8cWyG1SQ6Yj6Xyyy8FhZ0ILKWJHhsU=,tag:q/f7sjMLrCkMzkYfYltX6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
