apiVersion: v1
kind: Secret
metadata:
  name: dozerdb-secrets
  namespace: dozerdb
type: Opaque
stringData:
  NEO4J_AUTH: ENC[AES256_GCM,data:iZ/n33KxcOUWRTleiNlYVVW0N9MLRwmw7GAy/D0itDT+iIyYK7cGQjq7xcHfDaeKKXw+Jntp,iv:8XAK+Ut3ezeUJKJmj177dpnEMtw3RNNm2GlEcSJv1Hs=,tag:MtiBoyoWmleTbZZRvC+YRA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWDQwOXZwc3JXcGk1K09W
        RlgvenJCQ1c1bWtQU2ttenRpU3k5SHB4K1FJCm42SW5sUGRiaitCUFdRN2UxSlcv
        d0ZmVHliNVlkYVQrMnpJU1JxQldyTVkKLS0tIDFPNEdRK240TVMzT3BkY1dydEJy
        MjZlY2ZvUDEzaUdJOU03ajY0VTFNWGMK8FglOBaygkTufPkp+2QfTX3iS9cynEZn
        CHPuTAakZc5G68vh4kSkeq8fHloN65jmJsDmzNtRea0okYmh4SIERw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNTNROWpnMnYrUG9zdGtL
        Qjg4L1V1dVNKcGxxb3RiUzA3M3JNeHAwdTNjClRXNEx2bGxjNmRmT21vdXRFYjJP
        T0M5NS9IS0ZUOGxFdmJvQU1NdUVEclEKLS0tIHYxQTJxWFdMa2Q2OE9KYUhzd2p2
        ekNzUGVWT1lCYXJNMzh3WjZHbG81ZmMK6pFGDODMvEvBXcNlKs+xFJ3jN+XmYdEM
        clJ+fqAPc7wfGpXc81GomPZmLymhdAUF7CCvLuyQ6dnz3j89jRDQMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-25T12:52:48Z"
  mac: ENC[AES256_GCM,data:hxzQ48lHmM0OFUhUF2ub5n8GzC2RQGrMkyzl7B/lOd1dKERFjqURIEGVLW7zWsDs/3dTCCWknqDIAeP/f39fPGDCTvBRELPLYwoFwjIHzF8LVY+ku/9y8/aw03NI4px5IWHF1os17jmaCAs1Djg5AkykbXsk4dCVbx3HbtglcKM=,iv:mbVYq3vQ8SGPZ8cWyG1SQ6Yj6Xyyy8FhZ0ILKWJHhsU=,tag:q/f7sjMLrCkMzkYfYltX6w==,type:str]
  version: 3.12.2
