apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-credentials
  namespace: immich
type: Opaque
stringData:
  database: ENC[AES256_GCM,data:RzB7n6VK,iv:cHQZ0gtzRlDSb42l7YIViftqWLSwl6AJhQ1LN2klscU=,tag:7Foz1LIQ6xv18BcXe5yoyQ==,type:str]
  username: ENC[AES256_GCM,data:j26eTUuh,iv:Hxl+GRiN4plHrXDbG9okQplqYaVdZIt7/fQRGaW2G/A=,tag:+FzGuAAKbysCEU4rZ+OY1w==,type:str]
  password: ENC[AES256_GCM,data:8QC4JhnkctEQXzgv6BVUEG5Q5BCOi6J6orsSkkvt3r8=,iv:uSzJ9pWV8G8yMq6emPcTdYluCnojOYdmZS2K7tChkzQ=,tag:BA01tygNtWisFow2c4Mu3Q==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYmRubW0wYUtlTkJZTk1x
        eHhTa1A0ZzNSNWd2U05iNk1oNGxDTWUyVVhBCnlIbWRRcVYraG9GZHczZlo5eExR
        RG1YZ1Y4Y0ZYb2Vma2hBbHBuWDc5OTgKLS0tIHhnQTMwUWFYQXdkcGJCU1U1M0Zh
        K2dTdWs0SWdxa1ZnaTFLNFV6ekhhaDAKvTITVpQNfhxgAC8+rkWkdJXL3SANItyH
        H5c9PnYek+wdW3yxXmL/7PncG9CDUoKRATyeZ/17NZcFNjqR+SJDgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T17:22:42Z"
  mac: ENC[AES256_GCM,data:H8nSjNF2meS30gRs0aZYXOG3F0yI4YV8K/smikD9uWaQBl/V5hjn5DlaQQ62Tm9QIszC2ihOMIuxSAUxvnXtVtk/e/fbOsFnSKx//k2KnbWMyPs35+CSbKja7SHjqosprR6i6AhTjWe+xe22WT3ZWGIMje6fNUS9HSJT/8b1q6s=,iv:x6LC1QFTsmkRRpxHEh9cAD5v3mGwytkIpg8eRk6xyy4=,tag:v00nhaHm85WZnfDcc0OgnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
