apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-credentials
  namespace: immich
type: Opaque
stringData:
  database: ENC[AES256_GCM,data:RzB7n6VK,iv:cHQZ0gtzRlDSb42l7YIViftqWLSwl6AJhQ1LN2klscU=,tag:7Foz1LIQ6xv18BcXe5yoyQ==,type:str]
  username: ENC[AES256_GCM,data:j26eTUuh,iv:Hxl+GRiN4plHrXDbG9okQplqYaVdZIt7/fQRGaW2G/A=,tag:+FzGuAAKbysCEU4rZ+OY1w==,type:str]
  password: ENC[AES256_GCM,data:8QC4JhnkctEQXzgv6BVUEG5Q5BCOi6J6orsSkkvt3r8=,iv:uSzJ9pWV8G8yMq6emPcTdYluCnojOYdmZS2K7tChkzQ=,tag:BA01tygNtWisFow2c4Mu3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZFFvYmRKcWNSNWZrNGR0
        Z3ByNzQzY0xzUHNEaXkrbHovaThvbDdKSVdVClREYVMxMi8ybm16VVFadEdaY3k5
        MlVQOC9Ba1Y0enRVUkduaHk5OUtranMKLS0tIHFEUUZkeERZUzExM1lST2ZTSzZG
        Y253MmxZTXB6UkVLMTBWaVpETjd3WDQKwKgWYo7iIhS+fp3lyNlJVp1zV/MqTXO9
        eydzcRxa2kdv4eT6CX3b0set/6Ql2BoPK4Wl1asy+ZmHp5+PyiE+QQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRR2VmSW9ZQ0RmUGVmUGU5
        bnRCL215SGp0eXlzNnhQM09FTHp2cXZZbGhNCmljaFE0L2l6Z3BIWFljUUl0QXFT
        Wkxnem9abG1zSEtpR0NCNUZjR2VaajgKLS0tIFg4WWJoek5MSm9rSE1uTml2QjNI
        amNnOGNuYzB1VjVBc2FocnZRcXVqZFkKTa7dMTPvUwO1U2wdZAZ7Bj1XBKTr7ubm
        dzVAXUrsq2Yf8lTGraFSzwMl7IY7kc7b6UljZtA8a+a0zf6dbg9QRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-03T17:22:42Z"
  mac: ENC[AES256_GCM,data:H8nSjNF2meS30gRs0aZYXOG3F0yI4YV8K/smikD9uWaQBl/V5hjn5DlaQQ62Tm9QIszC2ihOMIuxSAUxvnXtVtk/e/fbOsFnSKx//k2KnbWMyPs35+CSbKja7SHjqosprR6i6AhTjWe+xe22WT3ZWGIMje6fNUS9HSJT/8b1q6s=,iv:x6LC1QFTsmkRRpxHEh9cAD5v3mGwytkIpg8eRk6xyy4=,tag:v00nhaHm85WZnfDcc0OgnA==,type:str]
  version: 3.12.2
