---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.0.10.113
    path: /volume1/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: immich-library-nfs
