apiVersion: v1
kind: Secret
metadata:
  name: dawarich-secrets
  namespace: dawarich
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:E7/y4hsqPkBhb1hWxL7n6jOm9PATxRWI9PoXZe8QhdNwThEpRfMNlEOz98pO+WomlrHgA5+iXa0D8ZNTR0z+YnFjcJjFbpI+PBbV/ltG4SCsriUnnHbjzrPt5xUTdRB9tJzlYrc63wr2UAkVMJYVYWSU8I/L/yCO/oDjs58DHjk=,iv:S6tTdVQk3N29FnbV5yvbDng9EY4hgw1aauw7hUknO1s=,tag:dcEZ1qYLifSy8fSXGPf4zA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:NCPh7/2GPhuNFfE6uataMzLXT9URLNfimkX90cwYm6lk3JNZ+M8UYZCBgeax0L9Q0yLNGlX4whLmHBgxka6RVA==,iv:dFmakSRzgkjRuKx/SZZ1bh2w4MKu2I5TW30AbOdPdTM=,tag:qGKLMFv1qflkE/7Pv3oqhg==,type:str]
  OTP_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:uWTRkmhI/LsDM/KeCiqIM7CbmyQDX5ARmK3SJ6MJEKNto7VmpXwKrizUvYgrxk+omLS4wu616FSzU8Y8zV5mbQ==,iv:1fpmpTY8YTTxXp4G2RD4zAC+rBK3hA6my2CFzzg02FE=,tag:xQDgUxCWWcXdgg/TbBwnLw==,type:str]
  OTP_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:qftJo2cphrEnkMWwue3aQZFhLux9lUslcUiAbc+/Yd3kFf4+vOOOwxIF/XWVb1E46i8ipksBNgLXwopiPO5wjA==,iv:DwBNNkZxB8JoFCKVCffwm1+lAjTGtb+Y8lXFlox7sLM=,tag:CWAgcpZKyjHXdVn78UYvbQ==,type:str]
  OTP_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:VrNjby5hYYV2hihocMmUtqkT+rQPGoU7gq9X+vq6eFaFi3eOy7ooZBpFQkrx658F0AeVFCbhBeCbPMJlI68yzg==,iv:h0QSWsYTFCaHMkCEl3aw7IUDDZXwfd/wePchHZm/NL8=,tag:k1a05aWIqlBNR0Cqx3pHgw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS0Z1ZmMvb0VIdXNzZGJ3
        V2FjUUhoMnBpWm9ZbXphNXhDUXplVjF0T2pBCk1JSUxpSFFGUm54QkY2ejhVZDV3
        aGhRSStIQ3VqUlRNSCt0TWpxQ0oxTEkKLS0tIGlyS3FRK0lHYVZuUEg4TjdpelUz
        VW03dFQvSHNtd1VOQmlGZVA0SjlkcTgKcdxR9JO7zU8TUN0EmjyNdCFQPAmyHyJG
        fyMXU+e5baiuVpSx50WgFLkqDfNr+vubt27M9KKbkBjxiBUGwec7bQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaTBPdGZQT2p3ZTJaVUpT
        ZFQ4dmpzUFdxbmdibWpmSUpJMitHQVRIOVJNCm5UN3RFbXVleTFzOHpTOHErcDFE
        Z3E0QS9LbSs2MHVZZ3RaR3I4SnlnUGcKLS0tIEdqQ2JXR0Fvc2NabC9nMHlJc1VF
        TkxDMkl2ejUzVlJORXd4ZzY2UllTbjQKCSeT6C/A5aLu5DtjJ2HyRBYLf/omjJpw
        PZM6/+NOKk7iEHyZpHTKtRbDrW8BFHFlRyu4jax3R9LHu0O8sFtATQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T09:51:04Z"
  mac: ENC[AES256_GCM,data:6U9dM4Si24UfYLuupAjQvtpgqfRZNFOHlPx35/q9nKAXc3mG35lOuyBSAhFKObJFmNbJXTjmwNj64RCIaEANdoTsIMqIkE3ChhDsS95YfEyMlkrzkkPNUQgQDczd/0Kmg7DVrFGQp1KMcWySd8llaNadMPBfvP6fwzIldaRGxDQ=,iv:V1BmZv87MlCE5T/gdBgx3dnISmbRf3c6LTjPL4tRfx8=,tag:Gs1yKTIXuh8L0FONeDBb0g==,type:str]
  version: 3.13.3
