apiVersion: v1
kind: Secret
metadata:
  name: dawarich-postgres-credentials
  namespace: dawarich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:6vYgzdoTXAs=,iv:ZZoeHcK62ITcjzEH6KluNzwHUZ72tnVONYJf9vUABUc=,tag:YCh7+1W2MeJ8m6dcxjGgqw==,type:str]
  password: ENC[AES256_GCM,data:rB4K1UECKV/Q120Bi6yqwM7VsWF0F0GezSQy6g==,iv:Iqf4rPnKplg9CKivxM+XnksOqdBXPrGfHZ/6qbTA8oY=,tag:SX/zIPzvhJQtl7U/a+CMJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWUFFSlVWZDdsR0ovQWtk
        WnAvOWx5VjVSbk1xMkRHVHRVTzJpa2h2a3hrCmI0T2VTanNmeGNPaEFmWXoybGVm
        bmgxcHNuRnhOV2owUlRsVWFJMzdZNjAKLS0tIHFxLytzbFEvaVhkUldQdmdQVFk2
        RHRHMCtwUVFQTkVQa0JWTmhqZHdPY3MKrwvdv/ZRVtm6UqiirqRpnUoDUtQmmnH3
        29RfxI/JmnMXd+YybOYttCysJRTvskuxYV0KJOZNzzAa6Hf2Td9wFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb0tqc1pScGhKTlZhZ2g0
        aDRQZGY0NVVPTmhLYk5YSG1USGl1TlBkajFRCkN5VVgyVnMxOWYyTG1HRHVQaDNQ
        b3hzeHd0bm1MaE5wL2pJZGZxSCtMa2sKLS0tIHQzbFdLMmZzTGI2bE9EMkloVDht
        ZG93eFNDZVowMGdVVHliNEdyRkRDWG8K4DitgG+/BFQLq/krQ9mtfuw5wNr/H/W+
        oF8QYlB4GkZR1NQOkE9yfky006LqblPpJklLOYn+Tr4B7DvpbsNl2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T09:51:04Z"
  mac: ENC[AES256_GCM,data:XTjmlUzfNPGYfEpmhlzfzTg8s7yibYAGQ6AxnNk6zX+P/JaesnxRXkrpHgCo4KMXMBOuFMmWvTPGGGYylKF/cq4cnUG+DxujPYNzosouOWMbdBR08RO76oJr/pBa1NJS2IAeuTrAU5PqonaAa/0AD9sR9YDCiKlWaDz5nWL+sms=,iv:E8UBdfbCIr95l5XSu82FcAQiNjS0tICGexLFJYlO/kQ=,tag:Sqi7AHRA3joKtweDEbBnWw==,type:str]
  version: 3.13.3
