apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dawarich-secrets.sops.yaml
  - dawarich-postgres-credentials.sops.yaml
  - valkey-auth.sops.yaml
  - rustfs-s3-credentials.sops.yaml
  - postgres-cluster.yaml
  - dawarich.yaml
  - httproute.yaml
  - dnsendpoint.yaml
  - network-policies.yaml
  - kuma-monitor.yaml
components:
  - ../../components/network-policies/base
namespace: dawarich
