apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: dawarich
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:OS1wGQiEfFeChPAu,iv:UQib/cM184XFOTYCmu0H0dT1kZqwLpuIs3Pls29au3M=,tag:lG8zB3jJBU3wPpGgp6j+zA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:a9SbSGLCMcA9rNziTu6waorGftgF6GkZ+DkgjjbDLmNCanC5p5xY4A==,iv:rK9uMUEhEKiIg7tXs/pLTXwcjOlQpovP2S9d6Glxnck=,tag:PutFDDRjKtSLc2wKHyQa/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNGx1VWtJWUx6ZUY0NGRF
        UWJEZGZwSVI1cmQySzRkZXJlY1NyYU52RUdVCm8yMGVpZzlaWGlJOHZ2MXk3MGtI
        aTAweTYybGtoODVYaS9jQkpXajVwOGcKLS0tIHM2eHI1T0Z3SXJTd2dnaytIWXNk
        ZGVlYnBrcDJDeG9Ob0krU05EcExqVmcKQ9mWn3GkwOqerJP39+ZtTksfB+YyXo8E
        9U0VnXiq6gBWrffHqsi8UhxBYybNiQ3G0njRJfItI9+siqceZJp7Pg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MGlLRHFLVHhVK3l3Sjhu
        SGtjemI3NFpHM3BXWlljUmVXaVYwOEsvZ3l3Cm51RmpXWjBNZExCejV4U3A1aXhR
        VHA2NVVkcjluRWlwSGRLTHV6dXdKRTQKLS0tIG1ZSnk2c1dYSmlCRldPaHlqb0dz
        OWs3VEhkc2hPOUN2bm1GL0RxTEw1bGsK8eMNmR03uQjeZqIMR5nAvyYcIyqStHhM
        RFwHcvbKx0dEbgiTThuMJnE6NpwEhgI4OHBHSASpFKFmeAtBUXX/Pw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T09:59:04Z"
  mac: ENC[AES256_GCM,data:u80tWmxcpqQ5tcYIW6Buz4DLDC2FUvLMqZCuN0QjYu3hCqOdNTbewsqSFiTtAiSCOThevjXkIdlA9+FLK/zm+b5tK2dH0jkEMmQX3grz3TFbaddt4NN6IS/PqMCLgrSOPhz1wkzUH4Rw3pC+P02uJ4HULrvFaIgsh3pFYXP6cVM=,iv:emeDnVcac0wZ1Wa+113tun41Tb6dZcvmzpWPjpjkJ0Y=,tag:4tPnN0MsJdivSeRYzJ2B+g==,type:str]
  version: 3.13.3
