apiVersion: v1
kind: Secret
metadata:
  name: ring-secrets
  namespace: kazimo
type: Opaque
stringData:
  deployments: ENC[AES256_GCM,data:hGyPyA8YtgqYQ3+SNOpRG3C3oRUbZpFW2CsiHBLiX7ENDuZ6ZlZsrFff/Tcw7CHdJA1BNBFk/QaPE/Vxy1gA9CdpOArucBXr,iv:+Bf4ihbHBrMj5QGLbXJ6g2uUyvvCpJtZOrceLjfvAYw=,tag:Y0zmNEGVln0BAfJPB/BimA==,type:str]
  AuthKey.p8: ENC[AES256_GCM,data:20zUwFxBYxFkWX7sMVbVwX6yVWZNjErte2H4OB8PAIBzCjXXjP3QL2XaHUARcJxSJSZ5wXjUZKLkG9QfqyO5nA5aq/A8d3HY7sS1x5WNDgFBJLRiXI4g75qgGNmVIQqSAxpdbb/cLw/QFt9epORWyh6IQu9EXwGGkjxYg/SlXSMOs98JLl3d0WV1T5R3IIzb7P8kAkYhWRhWlpkyRmUGC/c6vq+5Oh0kDYDsI0+TCRT4bWo+bhEOmy1VGO9S7RJOzrzoOHfxx/WXW5bM0Xchw8F7STiHcXEcFfYZ6Wx86D1U5o6PWw9bgnOvZxUiDp1dyv7rzSmMBC1js5WPzrEin1WD,iv:eqpyXQx1ozDjsIEzWA1xE5JbSLyv0/swEqsyq/4FALg=,tag:IjDwd0XkwFSPKuRdyZ+Gzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOFpzNWFsTWdtdDdQZnpu
        UTQ3aWhTUG1nODhuZ2tSNnpycUJZRk9pZm5VClE5YU1lb0Vhdy8xZjNzT3FySWM2
        L2NjdFI2b1p2cEYrdVRhRmg1VmlpWkUKLS0tIHE1OUg3Szk0OTZ2Vi9FWXNzOE9J
        aFQwRWU1ZG5Yd3BUNkp0K2RXbC9iR2MKfTpTvdlWFGZM2IHgxFtdDj+INfe+mz7b
        TdzvlkUOWnyBjG/4oCewPVF63kvoU256Y0gXRRR3m4X950XrhJ4Ifg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYkF0MHlZa1ErYW1aWjNw
        RkQ1NWNrd2Q3KzFZNHVmQUY2b21UUjRjL1FJCk9FR1oycDQ0djN1bk91NUlMRmtu
        QnkraFVyZzdmRnB1am5JRVpzTFlHV1kKLS0tIDJkbFVjRHdQRkl0dmM3YS8wbmsw
        OURGcndLdXQvVzF3RHZ2dHE0KzI0RVEKWtPVoDrYoBY9BvTOBLHYOV0idefKYaoj
        relAVu5tCbFPDVWFCOMEi/uJolJJNmtRAA15Cu1f4UwlKw8ny0GHKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T21:22:43Z"
  mac: ENC[AES256_GCM,data:jFKbqtXDtEvPzVHtL1p3klgOGGs5x1wBP42QErrF1BaTrloZ6qAiCZ5XPHuT8Iqk6JA5nbpPadmRNz3PaGnXj602PIF7qwxoZ/GO0jqr/dHkHXj5PpRjfORKGERWZhDut9DKdEYDLZLvwjj/Ww59+oe63a6oGLtO6HGsdGB1VMg=,iv:nfwxE+MlIkxr27H8T1j5zEfxvVlQLZOZ6OvO7aYpssk=,tag:k+qh4yILncwRqUJQjdTPfg==,type:str]
  version: 3.13.3
