---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: intel-gpu-plugin-deny-ingress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-plugin
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: intel-gpu-plugin-allow-dns-egress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-plugin
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: intel-gpu-plugin-allow-api-egress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-plugin
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
