apiVersion: v1
data:
  EKINEKO_PRIM_KEY: ENC[AES256_GCM,data:swcQaNnCZr7CBwnK0Ivd8ZJn+bsjJSfwgVxBOGzzAAjbYnmQP8iFIKIRPRs=,iv:jNLBb2DxG6wiNjhAxmg1R+sjt9ckFRO929o/1AtgBwg=,tag:0i2IN4BYFTRRvPGLRxLHpQ==,type:str]
kind: Secret
metadata:
  name: ekineko-prim
  namespace: ekineko
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncG0xbHM5VVBnOUprNFR6
        UDVHZEtaVEs3ajBpcHMwOHVuSG9VZ1F2OVR3Cm5oVVN5Y3IrSVQvTmVwOFArYzNy
        N3drbzhsK2JpdEVwdjIyWWZZM0kxTnMKLS0tIFFkeFNmZ0xCdE0zc21zS0djQUdG
        UzJsMlJ1QTl3WGk4aUpqaWF4cjI0TU0KETkdLMXRsFtqtN5xCezXjRjHMioE+i1O
        c9TDZM7VoSz5jHgtk9XpC+XkHWdecFjYgoHUcgG2Xk/HHwf1co3uAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaDZ4K3Zyczl0QVNGcFpr
        OG9pVXJVSzc3eTJLSzlpamVWcW14OWEwbWlVCjRid2ZhVGdhYTdtUEt1ZUkyWnRI
        VXY3LzJOaGx5cTI2dlhWQ1NmOVRaRXcKLS0tIE5NOXZvd2JrTVF1SUNBUzB5a0dv
        RUtxWk9xeHZ5eHAyOWc5UUF6UlpSRE0KeWp2mTfHTsITDRR4LL/G70eP2Mc7FSfN
        zmpe6ZQi3vpp07/TMIGVqMP5PSZJj6qn6dkVWnd+H4ULrL4UWubjvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T15:04:34Z"
  mac: ENC[AES256_GCM,data:WNAV6KUsUwDIJpy20jYlKUOkTJKtn3Ook3gdD04da8QOhIHy1/kUFVdYEahOkKWDPSy3+6rqEBdjwnJxpEMHSyPXwZ2UOE5JPbOYoRosMVCS68n/MneKAUWwVualM6tvvKy68Y27mUEfLfQQv0gR8rHyWcIDoM+xK4Is8YKOp8M=,iv:XsJrPQw5JeQ6A3nHzVXM8T/gHyzgkfcCMVrOvPmKuCQ=,tag:EFwgfxVvPlcaL2WWadryhw==,type:str]
  version: 3.13.3
