apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: ekineko
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:/KgIrmzWbBAo1015,iv:5Ix87I7nLo+8BKjlzjkwI2XGuKceirogKquVGmo0lUQ=,tag:Jd87BibGnpNyK4ZqAv4+iQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:jzQ7y5Vrk7rTR4XV2LWQ6+ZPDI0TjwRX5vjUODoFGXHb3D2ZnoBOVw==,iv:BhFQRlj7DOR1mSXq2jXvHYKEYEUAvZbIzvMQfpKDq6c=,tag:wpDbuEBMGM9Z7JKGl0yCLQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dmRsVXAxd1E0UDlMK3RV
        OXdjUGZ3NUovV1RaOW10U2MrOVFiSHpBZVVrCmNWZlE5K0M2cklCUnFhTlh5WTZt
        RmI5L3cwSm9YeGZGazlmc21kYytZSU0KLS0tIGRVZE5TckdWazlrWU4xWkVxdnVV
        QnFhRnlyZmQvZGFZRytBY3hIYUFoNDgK4Dmrk9WYY5qTIzv6nIZd1ua+XnS9F2BZ
        0n+lDn51U0y9Z8jnzSnLcoeY4glzwYlYAq5DQOouHf2P2O8onRuXHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlakpGNTU5OVZJL1hMNUNk
        QjZJWXg3OXl5WjF1S1FaUlI1ZDNmWVkvM0JvCnZFVGNXRGdOSzAxaE5JaFg3bjlS
        dzJCUWlwYmZTbW1OZ1VxNVRUbytCOVEKLS0tIHJibTF6QTlkd3ZIU252YTlBTklW
        SjkzN05rdXhhcmNJSll1a1YrZmpuNlEKIoDjd5I6OUZwXfSI5kP6PnFJDLYxzjvF
        8sEVWuW3fTtFrFLP71kyz2V8kke6AOhymdIK8kRjtI/X5PDqW2aTSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T13:11:17Z"
  mac: ENC[AES256_GCM,data:E01cGiVgvXWNJN8d+znJM6HNUrgdMi6W1FkItEXvGYUyU0s+/3+cvxAncRkxx6gnCeuWlasCBFVM6vh9CS/gzVOML6cBrpZ8kwuddHbs825TmPcNO2paxPHXqpr9X5pIN1Xn4zdTIiSvKVCjeR56aQ/NsA0+SCaK61IW0iy7oxY=,iv:P76OCcR1r7ot0Z0GLexqUd9T5wr6IBsEOiBg4SAfMIg=,tag:N735sVz3M5O4aQvvhrCimA==,type:str]
  version: 3.13.3
