---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spegel-allow-dns-egress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spegel
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spegel-allow-api-egress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spegel
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spegel-allow-registry-egress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spegel
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spegel-allow-p2p
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spegel
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.1.0/24
      ports:
        - protocol: TCP
          port: 5000
        - protocol: TCP
          port: 5001
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: spegel
      ports:
        - protocol: TCP
          port: 5000
        - protocol: TCP
          port: 5001
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.1.0/24
      ports:
        - protocol: TCP
          port: 5000
        - protocol: TCP
          port: 5001
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: spegel
      ports:
        - protocol: TCP
          port: 5000
        - protocol: TCP
          port: 5001
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: spegel-allow-p2p-cross-node
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: spegel
  ingress:
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
            - port: "5001"
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spegel-allow-prometheus-scrape
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spegel
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
