apiVersion: v1
kind: Secret
metadata:
  name: hermes-matrix
  namespace: hermes
type: Opaque
stringData:
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:EnOLNld0tb+cd36+4jQ4Dz3RXwbhBd32onCKYKGyx1hQSi5edUJunHc=,iv:1+yOVQw8OAn1uehI+/Owzt2+hEGYMZNrehNPsd9DWwg=,tag:nVd3uqoFnwTO8QAhkC43DQ==,type:str]
  MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:J8vDMwewVKMtFYxR8OqMJ1lbjulaQ2O/LXgvvf0pDwSBJq9I0/0w37BPlLrUrGdkeS3AJMROuQ5u4RQ=,iv:QsVhDFmpFWODNyZZT4BtnKbnDZNaJhbbhlV647mUrXk=,tag:IIDIacKwYilppVgssN5mfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTHpyNmlEaVRWOHRNWHRt
        eFlyMStiNFdlczdQOHROdGppSGppaDBUc1ZZCktyMTBBVGw3YUFBcG8wdHQvaERy
        dVF4amVPTy93TVdLQTN2RURHVE5LY1kKLS0tIFBheUdtaWEzNzRsZEx6MWF2SzlZ
        ZWNzRklyb2NvbWQ5QUIxcUVRTzJreGcKCz/qHGtEeL0SrrX5xrXFFWTM6Ags0KtS
        jB5KKuVmEcSOh1vux74WGnHhWb0JjE9jFY5SnufK2lifyP1I0Liv3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T08:31:02Z"
  mac: ENC[AES256_GCM,data:Rq9DmbMDUJ3GcWFBkSuwGeYYWUfzeq29E3KW4eJEYNnWOHWUMfIMRcXReXYJKH6BLG88R+YmRm64Mauww8JLlbxc1v9AHKwy5akyccjMr88WTvUjRMsmeqvsRTGHdw5aw/PaxjtYgKhaTohL33IocVWouqLWVrtqbCBxp6Ci0UM=,iv:87y9S9QBrPNbnV6eZnWb9gmrRq8kpm0yuTkUjUVGiRM=,tag:A9FG2WiFEBvg4+yX55ah8w==,type:str]
  version: 3.13.1
