apiVersion: v1
kind: Secret
metadata:
  name: hermes-secrets
  namespace: hermes
type: Opaque
stringData:
  #ENC[AES256_GCM,data:slhdcMz3DDp7hLR9jICGSRzpjNUmbyl5regdLFNIxToZH8YArYLaI37Q,iv:CHBEhbJ5VjtCn6WJMX8rAHsdH2DLvuRJZfvJvjGKnlg=,tag:wbae/221qe1Nsf7c8Zmu3w==,type:comment]
  #ENC[AES256_GCM,data:z+4hxO17SpsHuzMp325GhK0l2d3L+48BM/VLWj1o20cItfjErQOKc7it9hTqLjumR0LUGxSoKsbi8SM/UDRbcxT0loUeMN3wpw==,iv:asOSIKJSX7TrdEGetQeUVw+wHHlw0jdNVsMgzBlj/6E=,tag:usUesw2CSE/2CjeP1qDIpA==,type:comment]
  #ENC[AES256_GCM,data:qgNYLsigaMB4Yh0Pq2n40BOEujehtxXpdMRTSY7kS0AZffCO188opBVfmgrlQYI+xF9x2xpCJxd92L2vigLVEEXsZmQ=,iv:vfoq/m/uSMblgpajTNMVs456bHzuSnM1uOfnUHjU6kk=,tag:XvP8wfNBQs7i4YKqcUgmsg==,type:comment]
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:9sjhsnEUuutjfzcRtjrgp9Zjg1nuj26NbSzZt5uJHDxhDOzMkSGeQrbTzsHYFPPBJb0rE54+oJfZg3Xa0D3p/PHoLAh2E5Fgjg==,iv:ukfzqdaj30zbY2lVogMfV/QNKKXps7Jkrwm4h8IcO40=,tag:INmEU9Vi1fxddfMj9IYITg==,type:str]
  #ENC[AES256_GCM,data:aVYE7rkRTtwqhwDx4+ey9AJRuYi2jXK06Z/9FGaUodTrl4Fe3Z/VZ3tSd9+IeJWFebz7Nxy5jUf7ofQlwCHhaEzXoA==,iv:kZi3yc5uwtBaSbQ4CEIQezyvMOhOPB/UJZPYH0D/G2I=,tag:9PzamZZcMqE1AabDPG5KNQ==,type:comment]
  API_SERVER_KEY: ENC[AES256_GCM,data:0BL/A0Q7RCqwG+pzT/AT9pJ38FCLhcTsoZJ+kDQ07X98DtTiTpyeJitkQ2j44abMEMKi0UjqIYYrQ1WD/YxF0Q==,iv:J9+DokPUT1vAzdzz0UZklZj5ibLeFUrjxA48L71d9QI=,tag:X9xKrFMnxvxBCpgiLd6NlQ==,type:str]
  #ENC[AES256_GCM,data:1qZUJTTyrXQwphI7iJtN+xLTMKCUUIuHjpru3Oe4t1CGxXJ9B6QuyF3pf0hMQ0cYg6Uzt4lP05eZSHM4bWoDuV5L1/Y0Bg==,iv:i2ylOfdsND0TNxOKOLN7Kz62fHAy7cx/OW+CcnEr2es=,tag:QfIXQ7vNk3R9g1pNmoCRKA==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWWkvWUcyNm1FcUpCTHBW
        aTFlT0dIaTByLzVLeUxITjBIS3NZT2pFN2lnCjBCaGdDL2E5V0Frc09yMTI5Q1RL
        dythZG9YTWw5bU5uUHVFZjZsOTNPZEEKLS0tIDVLc2R6S2hyd3p4b214aEtYRXln
        emRRclk5T0gxS09CRnliYzB4SmNyQjQKFz5nDVkEl6e6Iva2v5fresl+w63eEa7f
        oRBKPhkh8qnHs0+t67dGH9dUDvqJDXgdK591NfbIT6ai38qmocALJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T19:25:19Z"
  mac: ENC[AES256_GCM,data:tCKM4g499uvrukRP+oCdbh2qA7S9KWoOSJM5sCO8wFh29FHw+DggZoh+Tj8ClYkzNQLotXe6cPZA8SW7DT1BI3XC3DMhWiCCW/eygNYU54yVeFU0W+S1opPxzsPTH9xA3fn7upIUP7IH8efGwzX/EWuDobNlsySpDH9RXrRRus0=,iv:5Lt2OLjoBC0yqwgHKBUFDqMD+32lUcLqsxlMUrYamto=,tag:JBk++5pFO4/hkJhaPJaABg==,type:str]
  version: 3.13.1
