apiVersion: v1
kind: Secret
metadata:
  name: hermes-matrix
  namespace: hermes
type: Opaque
stringData:
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:EnOLNld0tb+cd36+4jQ4Dz3RXwbhBd32onCKYKGyx1hQSi5edUJunHc=,iv:1+yOVQw8OAn1uehI+/Owzt2+hEGYMZNrehNPsd9DWwg=,tag:nVd3uqoFnwTO8QAhkC43DQ==,type:str]
  MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:bdMy9nMf41LZGXoZBWivotaeoKCbK276VkgONvwH3wXBjbFv8x18sCVAlPo/ltoHxHofA6ByNwR+bCU=,iv:PbGdN+7cmlZ653w6zUfCmD0JkAKwcalmrrDSTxnp3+Y=,tag:1+aB+d70THVkq6kuBPYE9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWWd6b1Z0dHBPdWNkYjRG
        Q2ZxZUZ6RjZWbjlQVytNaWt5VGZiQVFvMG00CklKOTQ4aEpBeDIySUpNZFpWQjJq
        ZXRHVkxsTFFhSWNrZ2pSamVRYmsvOTAKLS0tIGdCTHRmN0Fqa1FSOHd1My9nUzRZ
        SkNtWTNXN3RwdEF1ZlhXaHlzdFpxODQKOVTBUxwAvZLys++Qud/MNlhHl/kn6g7I
        3bvx2ve4/aEneZlxKlzOVJyu1cKnQpMRx0KVeR/BSRpaeKWQa8lCzQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVThBdkFaLzlSZ3g5QkVL
        UW52a01mbFFURERLdXhBNXlsM1h5NXNGU1c4CkZ3Wm5maW9HaDNtaTZUR3FhdDR1
        T2xCT0puMjBqT0pvZ2dGZlU1MmhLdjAKLS0tIE1OS0FFM2xhL1Q1YVUyTVFiMjRH
        M3Y5N2RXdEVjY1VrQWF3QVhXUmc4MmcK/r2h5NTISTx3nClFVGGNgRrfMAujdgkG
        7F0bvffIk8urSPj/w9N8TCRwgLTqap21uWmaKimyq6cnVFp6osZXPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T09:15:20Z"
  mac: ENC[AES256_GCM,data:0wln0wl81KvvXElbrzyY+Jh1Fq+Ym5+wC1hHsks/hYVXDmOH46x9S5ec1Rz6LCAAFW0cJcziiz7EM0BgxTocAELlxFIjJL91Z+q+eTHK3yegT/UFYZs0ATWpM+/WOLialo2n9uyJHQdggdJrV+Sz3gv2Kwx/oUFlpPQQB3Wm9XI=,iv:GeHqaXs3hnJGZ+QLCZXvPlQDeKJ9krpBp64WFFoaftw=,tag:WJeRoa57skHT+wdUi2WCGg==,type:str]
  version: 3.13.1
