apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - hermes-secrets.sops.yaml
  - hermes-matrix.sops.yaml
  - statefulset.yaml
  - certificate.yaml
  - httproute.yaml
  - reference-grant.yaml
  - network-policies.yaml
