---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-homekit
  namespace: home-automation
spec:
  type: LoadBalancer
  loadBalancerIP: ${LB_HOME_ASSISTANT}
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
  ports:
    - name: hap-bridge
      protocol: TCP
      port: 21064
      targetPort: 21064
    - name: hap-cam1
      protocol: TCP
      port: 21065
      targetPort: 21065
    - name: hap-cam2
      protocol: TCP
      port: 21066
      targetPort: 21066
