apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - reference-grant.yaml
  - frigate
  - home-assistant
  - mosquitto
  - zigbee2mqtt
components:
  - ../../components/network-policies/base
namespace: home-automation
