apiVersion: v1
kind: Secret
metadata:
  name: mas-postgres-credentials
  namespace: matrix
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:3qOZ,iv:NzlEqJQa+yJdT7K1irr79xGwu/yRu4buphZO8Y3PXCM=,tag:CKehvruqP+7vvkpqfbtkHg==,type:str]
  password: ENC[AES256_GCM,data:SwLggrhBoGvaMxEQBS8Brpmyo3zFZ/WioDMz3OTMkkm6dYXGe+vx3dH1FfHJoS5/4o/JbT8LjEauMa0gZJN3jQ==,iv:NTsmj+LBjaGXfcPGP4UuDU/Lf2pkWNPNQ5qw0XwO9BA=,tag:aDulwWTuhkkbxq4k8tq2UQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RHlHVEtFU3FmbzR3T0Yy
        SWs4cFRoQ2dwVXd0bnlFczExL0owMm8vZ1d3CnNERkZmYXo4Rkl0L1VNenh2YkhL
        SHE0ZFhTUnFvN3p3UTBiSWt6T1pJbUEKLS0tIGtBTmhsa3NxZDJnSzN2TTRaTCtV
        eGxVVFFpOGZUN29BTXlKVkVxKytRaWcKR9HOV23PPXfhcr8BwWhisNEZCilikUZw
        BxNAKMzoW+jUZTF3PhlHgXMFNNSLfxWLoQQ7Q9se+P2SUijUbFzHfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T09:04:43Z"
  mac: ENC[AES256_GCM,data:xHZThH2viva1oDXE6O7MP9LzmopUXUHmEptTBEQk+7FoUNF/XVlK3/Rjtpz5sCUcsLiVFkScjhkQckg6B/B5YnZq8IgUgxNiBCXSYv6hAQXbiS4+nRekZfjubeLWxaYrliSBzfQNzgyn1J2sEABY89e1y4JrdZXhd6H9Rn8u2Mw=,iv:AWYBVIxnbFqHLfkoBEVFABghe3rC7htBU8OINKk9V6g=,tag:bFLuZDLfZEDZSd0Np8hnxg==,type:str]
  version: 3.13.1
