apiVersion: v1
kind: Secret
metadata:
  name: mas-postgres-credentials
  namespace: matrix
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:3qOZ,iv:NzlEqJQa+yJdT7K1irr79xGwu/yRu4buphZO8Y3PXCM=,tag:CKehvruqP+7vvkpqfbtkHg==,type:str]
  password: ENC[AES256_GCM,data:SwLggrhBoGvaMxEQBS8Brpmyo3zFZ/WioDMz3OTMkkm6dYXGe+vx3dH1FfHJoS5/4o/JbT8LjEauMa0gZJN3jQ==,iv:NTsmj+LBjaGXfcPGP4UuDU/Lf2pkWNPNQ5qw0XwO9BA=,tag:aDulwWTuhkkbxq4k8tq2UQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZERSSlFtUVhpRUgwUkJG
        ZnJkYWVzeUdWV2JKSzREblpnYkdSUnlDblE0ClZ0QUhQSVNyL2IvRkxiY211U0lB
        N2phdkIwYTA4V0IrL1d0ZEJQVFdTRVEKLS0tIE5Ibjl3NURqZUpFNm9jV2p1bjla
        VWtNdU53NmVIRHlFaWZWS0ZNaVIwdzQKAqma/sJhO5+IcRiPDCm9ooshICpYs8Sn
        ay9tOZfKZBQZXannHZxagVZ7NPC3/aI0lV13QkvtgPGUvwVwDWgmOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjenJzcVg0aDF5VFhUM2hB
        N2pZejkyVGV5Mkt3a0xlTlZlenExZFdlSFdJCmhVQjBkYnRBeFMrak90N2kvN200
        LzEycTRocE9vanhTWU5aSmlnUE1qZ00KLS0tIExISjZOcEhPeWNjbFNDc2o5bGVP
        T0pUcnRERWN4TVl3OElTMUJpa2RkVjQK1ISdfZiUho4+1CpQRdOXIPu4hmsSAIdS
        NMK7cUt+i6drw17tvfG0d6Stvx2EWhyrGzAim41WXf8tqb2xozgXeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T09:04:43Z"
  mac: ENC[AES256_GCM,data:xHZThH2viva1oDXE6O7MP9LzmopUXUHmEptTBEQk+7FoUNF/XVlK3/Rjtpz5sCUcsLiVFkScjhkQckg6B/B5YnZq8IgUgxNiBCXSYv6hAQXbiS4+nRekZfjubeLWxaYrliSBzfQNzgyn1J2sEABY89e1y4JrdZXhd6H9Rn8u2Mw=,iv:AWYBVIxnbFqHLfkoBEVFABghe3rC7htBU8OINKk9V6g=,tag:bFLuZDLfZEDZSd0Np8hnxg==,type:str]
  version: 3.13.1
