apiVersion: v1
kind: Secret
metadata:
  name: paperless-postgres-credentials
  namespace: paperless
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Ay2d8mowISXf,iv:yeMdwn1S7zKkZSnGjuJoYRDSSVyA7MN5HyhlNlgBzqo=,tag:cKuiUbNyOEv5mCdejXEBAw==,type:str]
  password: ENC[AES256_GCM,data:M0AXeAGLqinXTse0twNsSJXUpRk1viWGZ1RfR7Oq3oE=,iv:5zEiNhnz0INSiPS3TAuZdLoBgZRLmHzjEps17hqdzRk=,tag:OYu3+/94uMikeFAZJkD8FQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleTY0S1hBMTNTc0NvbzBU
        TjFrUjNycll3bXRoTFczRGJaV3hVVzI4YjN3CldlN014OFAzdnBHOXFqb09mdEta
        UFRYZGpPSDdXbHpNMFd5Z1U5eHN5VmcKLS0tIExJcTNnRkJjemZtZjAxZnU5clpx
        Ny84bmpaVU1sQWZVdUplVndNeWVFWVEK5Au3TlmcJZ7owAXMZ5NY9QcICptKp+Yr
        UHGRbioh3IKKBvE3Rg0yWi6h/SDz2mKtBbPEpywb+JMoxi3HA+x88A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdW9vMFN2NWp0Ymw5eUlZ
        WjNEMXlqdmU5dFdPYTJZSHJXWVpreDlocFRZCm5BM3NUa2tYVGk0N1VnOU1QTmZt
        dXJ5T0tZam9aZ05xSE02eVp4UURPSjAKLS0tIGQxSmNuZW5td0Q4aXVxaDJBUkd0
        ei9SSFlHaEF5aFdjWWhERWZKbm5MZE0KUCHn97RighQetvqQdnln2L+Ga+HcERnb
        rcu8+VFrPXHdsBB3do8KfcaJWl7SK1BjSuBEiZAwUSHLCMQi8nWuvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T12:51:31Z"
  mac: ENC[AES256_GCM,data:FllZSUelwFV1lLsjNiJfw0iIU+GvCrmXW0Yz7yl3BoLfpqjsLZDp/uCJ1y1LKhJLsR5Wc9H8xgSyS5228iVXnSMulPlzS9EPQ0/Bmm419Igjki8mct/TGBmRJ/y3+7XEFghtzX0YvdY1oTOf/2V471Zjp5ttuPq1zaRXxorB5Q0=,iv:IC2BxWqcuUDiIVxW5MEMEKneaiy8JcrJLaWeAT2ajnE=,tag:1PXxbu/+ylrmfPraQDeZoQ==,type:str]
  version: 3.13.3
