apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: paperless
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:uZzYDJJlTfszmEnKqhYo3Fm1ELvnvvCpbFlrDaehzdrAgwmmCKVQmR40ljsb13K0elnKU+0okvxUcrCsKIz8FiiLKZV8j0On+yNEny1o0xMA+Lfc2+Y=,iv:Rb2NW/cehYA/3tBc3ttByLHI+qtyFFkydPxD0oH3/Mw=,tag:QgDFMUQlV2XZlPLLp/QVcw==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:xzHk7uuQ+91GXpMnwburFW2wzEz+sV9K0Ru04OldzR4=,iv:7+OgRmKjlkOI38CU0WdWSpM9BCFO3T9Chuxcqoboxg4=,tag:OcsMsZoCOcpc3BFlvk3JTA==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:BA7ie7fm1LU9+0TUZW5haObBSkqxP/ACNXsB61wa7/H4O0ZGqFKPufPvNIfCQP5UMWjNyfzykJzINxBbOJYnO2ihedJsiHVt25KHlRbnjvsM/DAApj3J/P3RSGUeF+D7IEHQUQ4CBPBZ/Vh4n3/9ntzRn29/zO2s6akikNUIiT3kEWs1KfxQFPo2VPA5D9jrMaZN3eQUii+l1hPelqL0PSbBUzUrdlFBHmy5RqvU1XslZkRJpDJKfwKh3DCwQH7fTrFzT6cVA2U54QOJ6P+abwZIaAn9fqnse+97GLr3RLSruJUxf4ra8rcv954M/dYuc3ZlFf3LSnsNKAUZ4yaTce+MunTXvevQw3KW+ExwUaPTveLWVeEwOQFFvrcZPxL42mGwo5AJ+TTjuqjCyHWc8IOy3WZtyhSZ4LdDAxxcJ0ObMkkIzKkjTQ==,iv:AEQR+WxUQA67TLaAYEB54NECgxIr+/EPHWyslFgDlho=,tag:a/T9BNvZoyr7wzfB9CyvZg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMzErb3ZYOCs0ZG5CU011
        azloL3hrUEVKWHV0SEc3WXZZZGdRQ0w4ZmpZCkpuTlZMa283aFVTbDlCeThybXlK
        bkQvbHlsTkVJQjhFSXRrU3B5eVpodUkKLS0tIDhQMndYcDB0OVFSLzhlVGM3ZWFp
        d2huTHg2UnBpeHc1cUJCMnl3VXVKbHMKjGsdU0hvSDiYnt8aUMJZks5YtxycmdGV
        TfSKuWUGA1OUOCpYOCI/EqDrP8HaEC1aMR4iZdk2syu36vfEVXkLtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdXJMS0lMRFdiVm5meFhi
        SmdiTnZwSEI3S0tHcmhLbWhueWNYamZZeUF3CkV6U2lhT0hMSUtISzlXbExDQU8r
        MVpYc0UwSkUwcGdSbnRhQ2d5b09wR1EKLS0tIEllQlh4WDVoaWx2UU41Wkc3UXNx
        M0NIMUY5UnY2ZVkxKzVvM0hnM1kxVGsKJvrC0CtWhUkmfzpNg4c1nvvpzBD1MsR+
        026LJtt+/VzzeXTdEzuQjrSBldOn01LcN0ngclN7masPcKmQZjstbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T12:51:31Z"
  mac: ENC[AES256_GCM,data:KMi+oB3uSg4bNj4tdB4lCgov5n+5MVU0TNeEenFxoBgzXUPPFm5XK6YYEpnJ1lWFGYO+e9T45aoOZa+/AuamS90Su59x+mQQ6+ItLgz2maRBAW6ub46lQTWdesBW+cZEnU4GFbn9KKXJw6XhtViZw3Y3EDa2U+bJ7acb9Iq+FDk=,iv:QlsmuVcGAHDcrO39RdTCDn4iicLE/U3yPFAmvduOH8g=,tag:VXAyKaFNvhmWa5k+8i8LFg==,type:str]
  version: 3.13.3
