apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: paperless
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:eGQOUN3HdgujXE73,iv:iHMJUTwRnvix1C4y4BlyCAQp9lsBd2xsk+OD78lNIbU=,tag:ybhFN5KeCFcOrYYpx/cHXQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:C9IACMhRi755/H36F+PJCQUA+tHCpI8xWUAao74FHde/b7HrgokBsw==,iv:WrU75V907JXFvcVRr2LSKSyVLR+UkzavT6C+l/k0tR8=,tag:23QUZqjSB4YAcdIb+7Jkzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVitnZEJiL1QwYjBmKzlQ
        dEZqZFVkQW54Rkk5S0o3QmR1WlprWVgyR3lZClExRi81VXlSUnJkU0hMZ3Q1Z3J5
        UkQ4cFU5a21ieksvMW44MjM5disybDgKLS0tIFlyQWFaSitlWlFzQVR0Ry9PSnIz
        N1laTGpjbUcvZ29nZDJuOERwWU9STkkKMDg/lsF40bo1rjkrvyfo5MCC3wskT3SP
        le32Qx1ZoL4w0RnzeyTEcFwRkUwdGDXtvnWcNA7GgJdjiiWL6/mawA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNS2wxQlFvUksrZDFUaVBR
        TWxIeld1dmh6UTJzckZodzFLQWd3UnVsQ0NZCk1kdm9hN1V4R3dISDRhcGRRd1VG
        ZURQeDdabXFXWGVJbGdSU1ZxVit5RGsKLS0tIEVKRmhPN0hNNzVaSDBPVGpmVUZG
        YWJ1T2dHeGJpaHdKWldQZXhlQmNtb0kKJHSDndBcKRNkEjD4vrjOtBOafOJImpZf
        DIIattrBeuzqvaJJa8pUxQ9OdpN+zT5KH3GXen4wTuTvhRIn26tx/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T12:52:34Z"
  mac: ENC[AES256_GCM,data:uFm+9jRUsM8xELbRPA76lQIOpL3dHkNrYX+AqEorwAp9F8yj6LubkMZrwk3kK9IxpLlQVWyd7I6sQH8PhippeS7Vu3EFj7ZixS+Sj7e+T2UngSg05QjLMFwBD/mHTgMcn12RRHVNwDB1eyGGUFTJsX10NSLh/QvXkEPjUOE0dUs=,iv:IdyjsmJ0p4a8EG84tQcgcTrAJfnE1wmAlqVF+nXqXh0=,tag:19e0+3IEgQWfucAUNteuVA==,type:str]
  version: 3.13.3
