apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8rdI9+Yrhr2PY8pW0KAYkETgfXwdV2Ps6BGIMeMQrec=,iv:K8hOH/FMevSLJ4uK2Nr8DoO44F/KVujoogpbQuCZdSY=,tag:WzEV6dHB2RQ7fkmS4uuNQQ==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:48G0B1CSW81T7gff6bqSS+ZZ82lzQ+f7POueORwyadGE21KSE/mWO1TrKs7JyfNB5jRRIsFnJH0gSteyNeB3lKaWm5ZafIw79iDld8On4b1umRhX8FzDsJHNFV+Ts2JVUbYJjP7DtfacpOWJra+Wm2uqYF0h9BZjqQ==,iv:gAnvmZQA6yaontYlB38F90jPEjKPlXHpJdVxBz3titc=,tag:meUAFa8RVW2wCHiFzybhUQ==,type:str]
  FRIGATE_CAM1_PASSWORD: ENC[AES256_GCM,data:PQrglhHpk7TdcOzqkZs6,iv:1vxp2Ai30MRRBdEgFHRK88mOwwmKm3EhHs8ym5ji64c=,tag:V1KXg8yMuGvg6VHpvmcjsw==,type:str]
  FRIGATE_CAM2_PASSWORD: ENC[AES256_GCM,data:9oJjE2RuV/14SqPVoCyG,iv:nhztEJX7QjlU1UTxLBpDA7KruIyH7kamykNqnHi73ws=,tag:fw1BFiflbmZS5dRghuCfow==,type:str]
  HA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:w4GAy4wegx0LHXOOjJQn2aKtp73rJGKVHU78BYFJixU3eUmprd+BEIHkBg==,iv:yXodn5J3eo7zq8MW/M28TLlo4F9zWl3QivewmVsE5sc=,tag:Rm9l2Efh0F4y0zgeG+fbdA==,type:str]
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:SAwxrd4BaPRt04iN/bEgdjEQmAIuTFgFx/SVDfn2vqA=,iv:+GHQInhxHmt9pDdIJoXBZ9JOLMjtP7y+77iPmboSpo4=,tag:MOQZ3rqNICBZEfcTd8/Zww==,type:str]
  ZIGBEE2MQTT_MQTT_PASSWORD: ENC[AES256_GCM,data:vE5Yegg1H0P1ZYEF3y8Foj99dGmiYWbV3oAxZ1kFFLE=,iv:cVssnGeZgu+25VSILswzupz3i/j9EvMuonhyOUt2sQ8=,tag:Nm3N4Sq/Iosc0QwiExGiTA==,type:str]
  HEARTBEAT_URL: ENC[AES256_GCM,data:xCNb7c8iqrp/co9VHh+bVVNemvIVItYev+H3/tPVzNCV1yQNyTPHKKX/pUK7YCGxlYLB/GUqtpo=,iv:qMY+w0LTq4nY+E/m/3scK632fOWHBXqkh9R8ygYhkvU=,tag:jfxu6dKbW7LR/VRnvfZmcg==,type:str]
  FRIGATE_CAM3_PASSWORD: ENC[AES256_GCM,data:qIB1p46Dk7Mn0uJOyYPqfhgvkp8=,iv:aDRuNLmzAYy29dFPHGOd6QCzVxB6+VEUj7g48Fzhrsw=,tag:yY5A6tGNyoa0SpVapR0NLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQyt2RUZLbTR3OTY5Yit4
        R1g0Ymp5aExQVnpGUmc3MUp1Yit2clRwYWxrCk9CdWVDN2drYVFnaHhMelhsWk42
        NGhLWC9nbk9LVTJDNjRHNFlBTnJnekEKLS0tIEZOT2FxRFFoOStMMHJOVkJ2Z2M5
        OUJhV3pRNDBGanJUeStDaHJZVXE5dVEKGM3Kw/udjTMoogKwjc2KLOA38+hrw5GI
        9lweuVoqoa94hM0Z1oBiXLqMNwrt1whgIREqPEehvTGXt5N2aIIAJQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a3ZtM1k5Ukg5VXNnZ3U0
        bXBQMHJnV0E3WmQ0NkpwN3JmYU55a0QrcUNzClRBNWxCWXBpNWhoVitrTTJSeStJ
        RmhTMEZFcEZmcGtFSjYwNzdTaGRvUWsKLS0tIGRzU0diOXhlb1hwaDdOUUhZVDhB
        bk5nUm5FcGorQkZjSTZudVJvanNpOEkKvm+JhUAc6XS7V/FDocBuiw4ePrj5CA39
        QvATWOBij0vnH79MEDIV0AztDYTc06ZMIZNttQBkInQbmQnXaqCYrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T19:51:02Z"
  mac: ENC[AES256_GCM,data:ruSJ+uScODLpf+iIVHFI5QPboEE5pToo02GBiFYhVwAPdxxqJrUbG5Y+MK66PcuIuVLLTMPCaH8SqkGipNBWhsXxyS/joMAri7S0QqAfBP0tpRYyWW300/Bud0hRzoZGTVfZK5pGdVKdk4XNEP4jzA6gi45zNDap8CEbs8SwWTg=,iv:jkOGgO+pQDBdszP4mCx7JuS+dVnhwP5GoSYGZV3LYgo=,tag:yhtGkUFv8Ry5wmE8fFkEhg==,type:str]
  version: 3.13.3
