---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: "merry.home.arpa"
  TIMEZONE: "Europe/Paris"
  DEFAULT_STORAGE_CLASS: "longhorn"
  CLUSTER_NAME: "going-merry"
  CLUSTER_VIP: "10.0.20.10"
  NODE_LUFFY: "10.0.20.11"
  NODE_ZORO: "10.0.20.12"
  NODE_NAMI: "10.0.20.13"
  NODE_USOPP: "10.0.20.14"
  NODE_SANJI: "10.0.20.15"
  NODE_CHOPPER: "10.0.20.16"
  LB_GATEWAY: "10.0.20.20"
  LB_ADGUARD: "10.0.20.21"

  LB_POOL_START: "10.0.20.20"
  LB_POOL_END: "10.0.20.39"
  CLUSTER_ISSUER: "mugiwara-ca-issuer"
  LB_EXTERNAL_GATEWAY: "10.0.20.23"
  NFS_BACKUP_TARGET: "nfs://10.0.10.113:/volume1/backups"
