apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_PLACEHOLDER: ENC[AES256_GCM,data:TVq+JmV93Rz0Ew3QX57K9nIHQGseEB+bznKx,iv:XF4H7cfv2jpOKAHm8egFrNDdwNjBSa3YLDuws24Uia4=,tag:nDUK1DkBf3IAm5suicbsbA==,type:str]
  GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8rdI9+Yrhr2PY8pW0KAYkETgfXwdV2Ps6BGIMeMQrec=,iv:K8hOH/FMevSLJ4uK2Nr8DoO44F/KVujoogpbQuCZdSY=,tag:WzEV6dHB2RQ7fkmS4uuNQQ==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:48G0B1CSW81T7gff6bqSS+ZZ82lzQ+f7POueORwyadGE21KSE/mWO1TrKs7JyfNB5jRRIsFnJH0gSteyNeB3lKaWm5ZafIw79iDld8On4b1umRhX8FzDsJHNFV+Ts2JVUbYJjP7DtfacpOWJra+Wm2uqYF0h9BZjqQ==,iv:gAnvmZQA6yaontYlB38F90jPEjKPlXHpJdVxBz3titc=,tag:meUAFa8RVW2wCHiFzybhUQ==,type:str]
  FRIGATE_CAM1_PASSWORD: ENC[AES256_GCM,data:PQrglhHpk7TdcOzqkZs6,iv:1vxp2Ai30MRRBdEgFHRK88mOwwmKm3EhHs8ym5ji64c=,tag:V1KXg8yMuGvg6VHpvmcjsw==,type:str]
  FRIGATE_CAM2_PASSWORD: ENC[AES256_GCM,data:9oJjE2RuV/14SqPVoCyG,iv:nhztEJX7QjlU1UTxLBpDA7KruIyH7kamykNqnHi73ws=,tag:fw1BFiflbmZS5dRghuCfow==,type:str]
  HA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:w4GAy4wegx0LHXOOjJQn2aKtp73rJGKVHU78BYFJixU3eUmprd+BEIHkBg==,iv:yXodn5J3eo7zq8MW/M28TLlo4F9zWl3QivewmVsE5sc=,tag:Rm9l2Efh0F4y0zgeG+fbdA==,type:str]
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:SAwxrd4BaPRt04iN/bEgdjEQmAIuTFgFx/SVDfn2vqA=,iv:+GHQInhxHmt9pDdIJoXBZ9JOLMjtP7y+77iPmboSpo4=,tag:MOQZ3rqNICBZEfcTd8/Zww==,type:str]
  ZIGBEE2MQTT_MQTT_PASSWORD: ENC[AES256_GCM,data:vE5Yegg1H0P1ZYEF3y8Foj99dGmiYWbV3oAxZ1kFFLE=,iv:cVssnGeZgu+25VSILswzupz3i/j9EvMuonhyOUt2sQ8=,tag:Nm3N4Sq/Iosc0QwiExGiTA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK1BrN2NDS2EzK0Z0Qmhw
        dkJZT1p2ZUxidmFPSi94TitSTlkwdHVMd0VJCkJnMUlsTnVsbG95dUdQRnJWVWhN
        eDhhQ3AvSituWTNWWUUvNWNUQldzZEUKLS0tIDgyS0h3YVdzNEsrWjh6U05PNSt6
        dElRNERDZFU1cUxUazY1RktqQ0tlb1kKTDWUPNK2o6MSvzW+4Cv29RjLj/G7NysZ
        dEI+BWCvD4WKqLLRBTZ4fEVsoC+oPreqbjIXsVbVotxONpciJiYPkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T18:38:05Z"
  mac: ENC[AES256_GCM,data:5OdO1s2tTeQaxgN03ytrjkb6XAbTHUr55nZLcf0NagmVZ1AlCGS3Ym5G04ul2o6VsCOmkyXeBbDwMB7nO4NFl3lt/NhtOJg5xG4pqgb9wBJ7YVHIFmWEXZO9j+l9Yh0KrxsaCgtMRISFFy0radxhi8ewrNiRPBWRZFRzFX7dZmk=,iv:eFqZHKInyWu65BIMRQs//JssX5F+4E29iQ0lkK3WFNc=,tag:vgwxk8Wt1I9nkqZQX6y88g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
