apiVersion: v1
kind: Secret
metadata:
  name: valkey-auth
  namespace: valkey-system
type: Opaque
stringData:
  default: ENC[AES256_GCM,data:oruBNlihmHn+/DITlP7I1iLfBvI0NWiZBJVucr1srSsSsSvSF0OWK7dq,iv:2LtkjMBCqAFNuxADh09RCbCittW4dEQuc9fceCSzBjA=,tag:COKjyTnYWnEFwglSEgqqpw==,type:str]
  password: ENC[AES256_GCM,data:AS+jAG3/xPONl6k6JcQMn9SWPVOaBp0FVhSaxGqFCXEx/9PeFrwBeENa,iv:90DZBsiXt/oEP0jHa6kPEpWJCzphLq4Zwxg++NKnV4U=,tag:O4GDHHhW/EHxFx5xpX018Q==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcHlKZlFhakZld3ByT0pM
        OGR4RkR0N2hVMEV4Smc5dDViKzVPQWFUVHlnCnRzNFBWVTZEcGFqbEdwRG93c21u
        KzhPQW02cWU4Z2V5VlFIQTZwVnJ2SkEKLS0tIEtURzRmV1J3ZDZNTkh4aEJYY3ZN
        VkNpWVF6ZUUveGYwRlFuZjVtMFQyd2sKG9u6zIHCNIKH79i+F6wfwL8C0LinX3+O
        /2/M5+UzIRS8PO3b/HMAE50yFB35k46pnbSRN/VN0BM7D3/z7kp/HQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T18:10:28Z"
  mac: ENC[AES256_GCM,data:HF6sSxBzLM1nZ/bvehYOD0BhW2u/fZKwSLpvpSwhd0ihZa4PL0kkoZtQqDtDqyzFWGmFy/FleMKLCojmER1baQEwjwcCm4g0FyP7geIEbc6mcwczXmIScCq6nZTljcc2loC0axWaVi1kP4k3wHaQcDG0mhHWPhhwfwbG/2nhDFw=,iv:p4QpcYPsm7n3jZkbcy1Gc5a7UNYlFxHL1911uI8oi1w=,tag:MhWvBm7C51wJRWYeerfgwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
