apiVersion: v1
kind: Secret
metadata:
  name: valkey-auth
  namespace: valkey-system
type: Opaque
stringData:
  default: ENC[AES256_GCM,data:oruBNlihmHn+/DITlP7I1iLfBvI0NWiZBJVucr1srSsSsSvSF0OWK7dq,iv:2LtkjMBCqAFNuxADh09RCbCittW4dEQuc9fceCSzBjA=,tag:COKjyTnYWnEFwglSEgqqpw==,type:str]
  password: ENC[AES256_GCM,data:AS+jAG3/xPONl6k6JcQMn9SWPVOaBp0FVhSaxGqFCXEx/9PeFrwBeENa,iv:90DZBsiXt/oEP0jHa6kPEpWJCzphLq4Zwxg++NKnV4U=,tag:O4GDHHhW/EHxFx5xpX018Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAranFHb2hUaGRIQXRHWXRh
        NU5oZzJubkJQL0NjZGdTRndLRlFFa1lnYWg4CjJzS0RFY0E3TmZWYVM2N2drYVVs
        M2d1d2ZkdXMrUmxmbWZ3Y2dUNFJMc0EKLS0tIDhLQS8vMys5bUdFcmN2MEtmekpG
        QWxhdlMzcTIxa01aMXBXenNQMFl3dGcKSy4I7tG55i43X+cKgC/YlCTpRgc2m+hT
        CabarEK7HZskFq4xNBy/Rji4OrGlIaKA9mQPgRWWR20U5Nj1nYgrQw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSkJNNThFNXV2OUlDZHZL
        VXY1dWI3QWxWdm5iYU95QytSUnlDbm8xYzEwCitrR0MvTlJoUFN3ZnFld0JTQmNt
        aW1xSDU4VEpqL2hhWjBGQWlRNjVKSGcKLS0tIDFGSWlMODA1Zm9oc1JZTk55KzV5
        aWZHeWplQXdEL2hUb09OeWlSdUxFZmcKXuM+t46MbrwPyPf+NXGxjajJjcqk7MlX
        Ih+AOueftsLo+KlTKwSsoZE9Hn88shI5yw4RFw2xN9LBdMO1M7pr2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-18T18:10:28Z"
  mac: ENC[AES256_GCM,data:HF6sSxBzLM1nZ/bvehYOD0BhW2u/fZKwSLpvpSwhd0ihZa4PL0kkoZtQqDtDqyzFWGmFy/FleMKLCojmER1baQEwjwcCm4g0FyP7geIEbc6mcwczXmIScCq6nZTljcc2loC0axWaVi1kP4k3wHaQcDG0mhHWPhhwfwbG/2nhDFw=,iv:p4QpcYPsm7n3jZkbcy1Gc5a7UNYlFxHL1911uI8oi1w=,tag:MhWvBm7C51wJRWYeerfgwg==,type:str]
  version: 3.12.2
