apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:WormmBNpZfQs+gbs7l4Rf5OkEfVmqRKhQ6blSmMUdtHnYqMRetXId4oRgMfh/Fy3stiW3AM=,iv:3UbJYFGwibSP5yAkjZBOO5asdKoLHYUSE7tpAGaU0X0=,tag:lW8qYrDvEfVAfbDShVAn1A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZU1vZlJaS0RiWThoam0x
        QUxlbDdrbFI5N0lGUmRlRmlhMlpzRWJEeHdZCnVnQ204OVc0RlphRk9Fa3lsdU5h
        S0UwQXJmY3F1M1BxaXlGeEhuZkU3MEUKLS0tIGJIUkFXTnh0K0RXbnprbEtsNXNU
        NmNQb2VoU24wNnZ4V1dzdmp6d0ZBTWMKDbhjYDtrlapsMFHxMXMv63/6YF4+zYDG
        dfM5urOgspXl/QkZQk1KJ2MheWLoJgjlGkSv8AMU7E+o6kL8rUaf4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T08:57:08Z"
  mac: ENC[AES256_GCM,data:nSW8P2jHdRnLZHAb4eafnUXgbjdcnhC4LF0iXOSMrJZycDe2/Y/sEWrSCZ4bS/0ezAh1SGy6sdmFMkdpZy2i3GCb/KWGcVz+PZeAwWRAHtIG8Pr7DtjB5PrWpzIMoUovGDECUSc/O4cfL3hPPaOq0LLbRIHYlQ+VAxr46jqiDlo=,iv:5+Him6uCpXnW5QxNg7Lfva6Z0vQE+DE/nKsEW4m8fOw=,tag:dnfuYjrZWjD+1h0xP4K8fQ==,type:str]
  version: 3.13.0
