apiVersion: v1
kind: Secret
metadata:
  name: lk-jwt-service-secrets
  namespace: matrix
type: Opaque
stringData:
  LIVEKIT_KEY: ENC[AES256_GCM,data:8kR8DtfXD7Ds13kRYkH0,iv:K+IWxd1cTGN664/9+34/h/su4QHmLUO+hwZrFlBkyvs=,tag:V1oUTL1/31Dl6tYkwDe9Zg==,type:str]
  LIVEKIT_SECRET: ENC[AES256_GCM,data:1GJc2NCIIfwXcGzM7hKobngQJIQ8qnmggF4iB8lTdc6OOYjJDN3rYUDmlzKWzLk7,iv:8YggmW0ceRVY1VDStz5vn/bbPkYw5mMCxsQSBKExSL8=,tag:bRBwaY6gzU5nZcN4V9jpgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZGVacDBoaXZwNHZ0UGhP
        RXU3RW9YVUJPWmpyQ3BuV3ZjVEd3aHNLaUZzCkJOK3BPMlVsRklxUitwZzBYTE9L
        UHVraWU3aTRxblluSHo3dWtIWmlPeFUKLS0tIEhsWjRjYk1qeDhSeTFFUDdtUk4z
        QndiZGp0cHlXRG1vN1p4Y1E1MGJvQ2cKUHeF+f/1g42l2x4dTRTrXejkjtFeQcnJ
        y/qeatSeuiT7mOQ4kBSVuMEQiBA0YTozh9LeWniCv+SM3JCqifauqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWDFtT0s4d0R0Y1BIdjBP
        aVRnT1U4WEVHdm5zK3hlQWFvVzNMTE9zczFJCjVMclZhTmZIVWp3dms1ZzkzRFJy
        RlVaZFZsNG5pZ1VDc09uVHBUQ1lzT28KLS0tIGtxdHpSamtnL1Zud0RhT0N3U3Z6
        T2ZHVzVvcEhhU3NlV3VNdkp6aTgvalUKH6o7BrUGfK0RMXvJJguFOQhtM02lq6z7
        wrUV71jtl+LkAnp06YxNr2LRhXIyPPItCqwqVyde1undDNgjhfRRLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T08:49:16Z"
  mac: ENC[AES256_GCM,data:2MLvDxwqpjXgxKzg9DkiqkMg2ysHV+jdRM7AJDZbMVxIGBzCNDOPryHq/mt/+K4OfYPp7pVObvjO2rewWE0Yy7FsV6th1Aquo4Kpsf0tsWh/GC0KxQl6D8mbV5mWSpE0vgiIp+cCvkXS01tlK/0fUPy3FkSFUEFeQl9ElAhigVw=,iv:IMUfcJ3oADhLXC6i3oI5yMM9bqXUwXePZz+T4JOstng=,tag:bZGHhiCDfWnHO2e2TGNrCg==,type:str]
  version: 3.13.3
