---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.0.10.113
    path: /volume1/frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-nfs
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: frigate-media-nfs
