apiVersion: v1
kind: Secret
metadata:
  name: zot-pull
  namespace: home-automation
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:wM+WSXU5AHOT+u4IOS5c+byexQiLh81nWAYU4vRx2knpE7LmVVyrNTIfGbGkduW+YUo9qtg/HAC7Gcez/6kXdnJ25XQJeYUfV30o7CTkSupnAA1Gr7BwEJVxaAAULPVHbaumgwIYRQnaigvh0DPEZrgl/2rqGA6YaWPGt4ZHzrWGGDs4PBqvjxqXUSsiZ1E9V0caez7uBff1HpRea7fk/MtI,iv:ZlB87pvVH/xzMmIxq2pj7H8mB1v8Ojj0ThfTQOzK8GM=,tag:wmzX692Lcyt09LoIyLoDdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU3hUWG5UR05Mb3V3Q3RY
        NHhJZEx5Tm9RVlQvRldwYVk3M2ZneUxSSXpFCkpXenJqcmpiUmlZSlI2bnpZdzRH
        UFNEeG4wQmp6TWw4c1NoNmswLzVFcmcKLS0tIDhYbVdLN3hvT2g4VURkUTlPTEU4
        a3pCeEkrTm1oWVpIQ2VEQjllKzFFZDAKwDDcNQfFodyDXAbEzb+UMgmvSmygVMt3
        +q42/orelKCmez7vIG2TcFMwHonLwDKNPyWkBqtaVeoQf8UbZ8TZeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWDA0dUlLekd2UXVVVkdV
        ZHJQaVJCTmczU2tRZkcrdmZlZU5KTGtQbmtnCnZQVVNIOHVlRnRETm9RaHQ3VG1Y
        Z3k4RDNoSTBFTjl4TFZnbWFHRmphUW8KLS0tIDBWbS9NNU90YXVNNWI3b08zNmFF
        KzRqYkFKTVBlUWpJTnYwazdmekw3M00KT799JhYWNRmzj1eqtM/i3a7dpLsMKAZA
        /ijUGRJ8hoxAK2VZUUKnK5jpq8siEDGfW8QQQZwfrUO3A7gdfsFzwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T08:52:50Z"
  mac: ENC[AES256_GCM,data:LBKryrewQZ4aazHpxLQxHD6DR8RBLmo8OeqlvZjgtr3uZiJy6xOhnQCuN1ApVxAyzkEDL7CsYhiN3JWmXcltuwULqHLHhkOJjRAc7toGxLQEfcZBNbA89TYg65o2MiENk9NcRyOAuO89Zr74Eu6DOWD2Wl26eREuDFCwASwlqV0=,iv:hIAShQ68Hsr3ifxGWkS9yDy9xXlBZUjbjluP13PqFfY=,tag:VPWfibFRH5X91ncxZLGYaA==,type:str]
  version: 3.13.3
