apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - matrix-secrets.sops.yaml
  - postgres-cluster.yaml
  - synapse-config.yaml
  - oidc-proxy.yaml
  - synapse.yaml
  - element.yaml
  - cinny.yaml
  - httproute.yaml
  - dnsendpoint.yaml
  - network-policies.yaml
