apiVersion: v1
kind: Secret
metadata:
  name: synapse-postgres-credentials
  namespace: matrix
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:GTYqqM+Epw==,iv:vrIiV363QcXH82lGhPQHF6ctzkoHmeA9Uk9YFLoYkm8=,tag:hYKaoCDKW/eEoG8wT+emfw==,type:str]
  password: ENC[AES256_GCM,data:F6StYjayupF4ObLAibdrssnIdFYz2S44X4TVlXWrXhwZ1qFPDIObdg4P2Iz10PMh8DHkdBgoB89ajTlAwZHiRg==,iv:Hw9Vh4WWnRSa4Q+23zA/52EBu23/c5GaELk78UX8Bc4=,tag:2Md+5FgMcX5e3kCNgXxKJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsU3ZGZnNqRDBsNnNNYkox
        Q3UyUGJjYXBZazEvRGQrSFA5bERVaGZmb1ZrCll0MWxpNS83V2p3QktTYlpTTk1y
        MHkrQVdjbEE2alpkamZCSWdSSkl2Y1kKLS0tIFpMUnAzL0ZYRllvaUs3eGdCcUtS
        REQ4YURMdnFkc2VxZXM2N3ZQN05US0UKfwlcPj2w9a59iF3YojjviYaJFuDpcF4O
        IWXkeRCMu9Zat1aGWohaIY+94TffJ4BwNySBM4RME0SUPKTvWhSHig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T12:55:24Z"
  mac: ENC[AES256_GCM,data:S29ddPL9hcEnzkERXxtC0g3wccAdjFDUQBJWRJnY+SRw++IrCvKWhYQLv7IggY0Px4WJXdi3sQejxeVkXwVypSMPSmawwKGQHVW9OIxBx77MVUEzGEs/P5bprknwQ4GoEL4DAgm+Jh2h0EcxrRz6tNPy0ESpU3o8wu0Vy5ajtn8=,iv:al5Qc0tk6wfg54uLTcvNN4hlB9BeAvjFdQhawMNcf1M=,tag:wUHULe9hjFHEqdiHx2uDyQ==,type:str]
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: synapse-secrets
  namespace: matrix
type: Opaque
stringData:
  oidc_client_secret: ENC[AES256_GCM,data:H8qOgEC7uFcBcmsSLALflwZxzcCR5CeGZAL20ktu3UyQy1B7rx1ZkpOJA6mLWz+9I+ijGmsMj/h7lI2iuaCBFw==,iv:B2uc22ivjkgfKRONn6Gn+gS2fFPKB07xBycOryf2BTQ=,tag:E7Ig7ly8gKObAZfRh4QF+g==,type:str]
  extra.yaml: ENC[AES256_GCM,data:qVnu4hUhQ6Z9jDW2lQ5XVagGTUimzFtf/pRkaHgs0IB2iOq0WKjsqa0JOJjPPAXS1wr2eARCTyoeOTCFLXBZ3oByTxWgXzsOLufs/sbtZGPInsK8GBO1HHDmOqq4s5AJomITWq/heKDLK7fnWYKqmT99U4U1K5XNqo/OK87w7WDS6ZLoSl0kUapQCHmZWYYXhRW89tBymRHGMM9Wdl7h0WPSy2TWuEpkmlpmKTxxNoXhHNI5NT/tgHKKrSlokem46p/kvh8GNTUBt6qcbZW0k8UD2dUrNQPTr9wP2nvPTNudjmYeQNW+haG3aigcsPwcWK2jxWYwMSq/UXN42eWZNx063s4DuDprghOv6jCoylLyAyE9viqVj8l/Y0oyGXsKc5BprnGVrZbSWqWLZdpqJqsxJAA3wy7nFaWsm0rBSZW90IoaaA94pymM5GgzyHHvnI62IjGn8Z/VkA6qO4nNkkg8d7zNVbnX1gn+/roDFPvRrllcq1ElTXafa5quv8AnyP0t+yK72caUkeFYHDAnypqMzdoY4jCTgsuqtb4XK52O1Usix2/SwEJOG9D/pNofXwlAVVyisxwJCC9Qw7jKSYBnJPirEmuMk0ExTupsa1+MmVsMHfza4qDqitBE+z/19ZiA56fDzH6cLDtfFPdEndSiiBeNmU0hjVDVPgxZy9hQlQ==,iv:FzpVEfp4sC9kIV48DgdrQPIWYrIdiRZ8le/SjbFfhEc=,tag:WuwyQaT+Akg0aMg1VoeV2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsU3ZGZnNqRDBsNnNNYkox
        Q3UyUGJjYXBZazEvRGQrSFA5bERVaGZmb1ZrCll0MWxpNS83V2p3QktTYlpTTk1y
        MHkrQVdjbEE2alpkamZCSWdSSkl2Y1kKLS0tIFpMUnAzL0ZYRllvaUs3eGdCcUtS
        REQ4YURMdnFkc2VxZXM2N3ZQN05US0UKfwlcPj2w9a59iF3YojjviYaJFuDpcF4O
        IWXkeRCMu9Zat1aGWohaIY+94TffJ4BwNySBM4RME0SUPKTvWhSHig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T12:55:24Z"
  mac: ENC[AES256_GCM,data:S29ddPL9hcEnzkERXxtC0g3wccAdjFDUQBJWRJnY+SRw++IrCvKWhYQLv7IggY0Px4WJXdi3sQejxeVkXwVypSMPSmawwKGQHVW9OIxBx77MVUEzGEs/P5bprknwQ4GoEL4DAgm+Jh2h0EcxrRz6tNPy0ESpU3o8wu0Vy5ajtn8=,iv:al5Qc0tk6wfg54uLTcvNN4hlB9BeAvjFdQhawMNcf1M=,tag:wUHULe9hjFHEqdiHx2uDyQ==,type:str]
  version: 3.13.1
