apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: matrix
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:GMO3YqRw4xjKTOF6,iv:3Q62oUSnNPR1mvOUQMcb2Hf1Ur9A5Oy1zATMbIuunhQ=,tag:LFXQuwB3ARIGupGfGJ3g3w==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:LYGMcPxSRWl9Rsx1eLB1NGCxJ2RAtgWXAi75Wp4s3M2FTCB04tgnAA==,iv:L3Hk2Dl7BRJXDn8r+MkVmZJTL3kRePnn5BHEG+F8I4A=,tag:AXI7hRc09AzvP32DPEVQYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwelBOU214azNwYnVVMVhy
        Z3dGbU5IcEVGVXBqYlp2NXFSM1NPWHk0dGlNClNRcUhTSVJBVUlwcDZ2ZVJoQTkr
        R05rWUVsMmcxS1ZtbG9yNnVQcWg2R0EKLS0tIHRyaTZwaTVibm40YjJSbHBHd2lE
        QVF2Ulg3c2xleHgzNWhveDlock9NRkkK/OBTzEow1JUKeqDkrnB7/pkbE4pEQvB0
        K3DmtUHgc4g8cv78Jqrbs1ldol3gYqkfEKRpMhnuxN/kAkbjTZO47w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OUZNN2REWklwN1oyeUg0
        Ky9xNlJYNk42S3pLL3FodHhGRjZnSE4vbXpBClZDa2h6NllqSW5KN1FRaVdJN0JH
        VXJmZDJ0MjJwSEVjb016YmFYRERSK1UKLS0tIFR3U2d1TUE0UnVFUUhwWW1wTzZn
        cXNoblgwZitjd2NvWUJkenM0QkE0dDQKa6nn1sjIaNsfj6DyZDktnSSyopCCtLVZ
        E4qL1bFBXhpGuaeMM+m2UYxc96h6G2YmGEfrSRgNb0GcpImC+5nWSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T20:19:37Z"
  mac: ENC[AES256_GCM,data:mpzJ4NBfh8vQchnQBFIEO39yMi9F852Bgn5H7+QDl/mnh/E5+bnzOW7mfsvjFbU50gZy4tBSjNq+xooXblpdYPiEveAeMIv7MVuEl/d16MEQSeHSQH+41wkJoqrTuB1xfgM0IB4o3HYN/VJ7RLW3udtMAnTm2hTZf2GBe7i2wJQ=,iv:vmAdjCVwXVTDrKA6UxdqrQgkzUusEHcORM/tH2wThLg=,tag:v8z0hfnEaDAIRmjd4zgFRw==,type:str]
  version: 3.13.1
