apiVersion: v1
kind: Secret
metadata:
  name: rustfs-s3-credentials
  namespace: matrix
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:GMO3YqRw4xjKTOF6,iv:3Q62oUSnNPR1mvOUQMcb2Hf1Ur9A5Oy1zATMbIuunhQ=,tag:LFXQuwB3ARIGupGfGJ3g3w==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:LYGMcPxSRWl9Rsx1eLB1NGCxJ2RAtgWXAi75Wp4s3M2FTCB04tgnAA==,iv:L3Hk2Dl7BRJXDn8r+MkVmZJTL3kRePnn5BHEG+F8I4A=,tag:AXI7hRc09AzvP32DPEVQYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QzJxbGYyMG5Lc25JdE12
        aWRIcjVlaVlFanU3UmRaaUpCdy8wdkkvKzFnCkx4bEJvRHN4dm9QTWVpaVBrWEIv
        eUZZVW9TQ0ZrODYrSk1YZERoVXVVcVkKLS0tIE0xMW16U0F1ak04a0kxZ0J0eS9h
        RnpuQ2RySDlkczRXT1JkNjFxemREZjgK+d03Wv8O4d8qCPHs+qYPwqXi8Z+Vfw/t
        2r+hl0h4RQ2zzq07+Wo2bpR9kTW4leSl53fKN0WNryfVBhI5HCnYgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T20:19:37Z"
  mac: ENC[AES256_GCM,data:mpzJ4NBfh8vQchnQBFIEO39yMi9F852Bgn5H7+QDl/mnh/E5+bnzOW7mfsvjFbU50gZy4tBSjNq+xooXblpdYPiEveAeMIv7MVuEl/d16MEQSeHSQH+41wkJoqrTuB1xfgM0IB4o3HYN/VJ7RLW3udtMAnTm2hTZf2GBe7i2wJQ=,iv:vmAdjCVwXVTDrKA6UxdqrQgkzUusEHcORM/tH2wThLg=,tag:v8z0hfnEaDAIRmjd4zgFRw==,type:str]
  version: 3.13.1
