apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lightrag
  namespace: gaspard
spec:
  parentRefs:
    - name: internal-gateway
      namespace: kube-system
      sectionName: https-lightrag
  hostnames:
    - lightrag.${CLUSTER_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: lightrag
          port: 9621
