apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - zot-pull-secret.sops.yaml
  - gaspard-secrets.sops.yaml
  - lightrag-config.yaml
  - helmrelease-tei.yaml
  - helmrelease-lightrag.yaml
  - helmrelease-mcp.yaml
  - network-policies.yaml
  - kuma-monitor.yaml
