apiVersion: v1
kind: Secret
metadata:
  name: zot-pull
  namespace: gaspard
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:l2hcKV9gtz0G1eDWO7oyomkMRVZGuUDIr7opYT0CsLST9zTNTuXQ/7jtQ0cfNzZIdHtfX2u0Eu6h+Xb1gxEDMdEF33B9GN0s6FG2li33FT7k/gahZ7a7VQiAK5FDUrYMBIHspCHbIW3tuW6/QaLFkOlWBS6pq2ndO3gNnZvDs72MPZ2/Kai6yZ0kLVRo3EWK2qK/+O6M5+z3rK2E1dAidf6MKkYq18E2sGdL7N8kcgne1oR9uACVcbahFPOCaVnfrmRSx6i/bd59HcweRkPtUBa7L8/O7ILp+g0kU++z1OXbjO6o6Bt+OkL7lj91dDmw6nxfu8Bo7zWPTBui1c4DORHZlhuRiKBzt5Nf7xDtAb7nHGUaCj4Tm2D/9bZJ1CpYL22Feh49qNj+FZJ54IX/lCcv6yrKweRaiKCTDi2asnRAEddOc3v0onjRnFgA0M+57PA=,iv:PGTEGt5f+nJD8voVP+7oHYRjYeOu+QSx0bCWKzb6HKo=,tag:123jHQOfGZkNE2tMFbs8+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbDZMMDBRRFd6d3A1alN2
        WXIvSHBVOVFyZ0hmakxKK2NKeHRKcDh2L1MwCnNxam1yZFZaOEc3ZUYzWkFpWTRu
        QnRjYXpTdXFMdUNxUHFRbHJWWnljeEUKLS0tIHZlYm5ucml6NFBuMHpYOHFWOHBR
        ZDhPZ0IwTG5yMXY4NS9SbTQ1VnN3R3MKrSeIRl3dR/Y1zvAYyza+r5yJhJnfwRk9
        cCqz3bEwLxbhOrMVMF3CT1j9r/bPlXPYqgDyZB5AmSjEuo5FEZ9Y8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcFlsb3NTNDc3VTJZK1Nk
        OUUrdTRvMW43RDJ6RG9pSXFpTFFzelY3VjBNClVIZHZvRFp0dndFenNoMEFPZFBx
        citvL3RxMkZnSHlHMG1vckdobDBUdm8KLS0tIGh2SnNLWWFaUnBkS2VFMS9ORmdy
        N1g3YVlsZ3FNUzBSaHlockpvQ0h4N0UKJqzC3tNlLxgDl1spxHjSL/8aTx7hZnVC
        pem6hVJlNN+h1q5kEt+UcA2DGBKITzGqrdjBCHIGqwwUQbR8LLIJWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T12:32:46Z"
  mac: ENC[AES256_GCM,data:CUaknA6ongu/2XuEVJ9yp6/yjmuJc2VRIiLuFhkidf38tDQkh0RSb0O/m2RDw2XZenVX+JCkz5/w8DFaeBQmM1j8OjCSkyBPhuXSi8izJYgI/JTchtTUskpLKDpQaAoryEoaCzKOKQ8i8CcwL4/L0QShz/KcEiaFropN+5XTuU0=,iv:MBMi8PSgf/BIl/KQmWhn0/UXf7Bi1wGSU5mnH0+eSvA=,tag:uEpjnwYfSCTs5XEcmG3wWw==,type:str]
  version: 3.13.3
