apiVersion: v1
kind: Secret
metadata:
  name: zot-pull
  namespace: gaspard
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:QWvJ7YOkcU/dND1tzPBrWFR0KsxRMLV0WROnFybQ0RLDMyXsB0eCCe0E1AMrCx6Y0zHnQNIkZJkdRCwcAfZ7N6mxSu0ki078iYetbxxGBdEjw+UcwE/pPRaO75qQIOwgTv3aOD7GEu4gUVRVbWi3ICGfyJItLUpFskBOITTFFygKsjC3oMtkapfI7Kbo3Je1FMGR9/UdC8BE1ZlwRcqLZwir141OYPxq6A==,iv:tOKYfsIGesN6g0x+NpI25zB1rybF+xjbQsQrYoUWbMQ=,tag:gmzM2pb0De5WyquVx0Fq3A==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNEJLMWcvdkgxUWhkRDJs
        Z0ZMdWlxSllkWlEvNUhJMXZzNGxqR1o5cEZ3ClBadDBwWHEvUk51OS9EUzE3TXJS
        bUxHR2x2VjVMVmRoWVltY0ExOWlVZncKLS0tIFAxeHFoWlVNeDc5MkxYeEg2ejRX
        eTErY25FRStybmtQc1VPWEd6ZUI5ZmMKohrXSY0frmy+Nw7LQ4qbqVx86ViVqZfZ
        ny/NgeUYSOQXPHQzw1lZQeQHHn5B3p0jkTG9vr2I3ZEsCMc50inWEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T22:33:13Z"
  mac: ENC[AES256_GCM,data:7fFoCjUvvododjxrYOi2VG2xuu2lhpJQlcDrOA91nMvmlF2nPoutKm4v5Ivl4imTsQHhqE/KsDNaR9kI2r1ISAiWWqdmjgqzS5FfAVG986JGncgBj+ZstbZEbg5T6cVDe05GEdwWUKR5FJfmDyR2NvYCq8bQlr6x2QqY7cBF/4M=,iv:oUTVrDKUcTUuh3lIkSZDAtJxwDAIDzY13EcPeUgA8y8=,tag:vCvl17Z4jQ6R5ffOFvcvOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
