---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: kube-system
  annotations:
    io.cilium/lb-ipam-ips: ${LB_GATEWAY}
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-auth
      protocol: HTTPS
      port: 443
      hostname: auth.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: authentik-tls
            namespace: authentik
      allowedRoutes:
        namespaces:
          from: All
    - name: https-grafana
      protocol: HTTPS
      port: 443
      hostname: grafana.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: grafana-tls
            namespace: monitoring
      allowedRoutes:
        namespaces:
          from: All
    - name: https-hubble
      protocol: HTTPS
      port: 443
      hostname: hubble.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: hubble-tls
            namespace: kube-system
      allowedRoutes:
        namespaces:
          from: All
    - name: https-longhorn
      protocol: HTTPS
      port: 443
      hostname: longhorn.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: longhorn-tls
            namespace: longhorn-system
      allowedRoutes:
        namespaces:
          from: All
    - name: https-adguard
      protocol: HTTPS
      port: 443
      hostname: adguard.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: adguard-tls
            namespace: adguard
      allowedRoutes:
        namespaces:
          from: All
    - name: https-homarr
      protocol: HTTPS
      port: 443
      hostname: homarr.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: homarr-tls
            namespace: homarr
      allowedRoutes:
        namespaces:
          from: All
    - name: https-frigate
      protocol: HTTPS
      port: 443
      hostname: frigate.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: frigate-tls
            namespace: home-automation
      allowedRoutes:
        namespaces:
          from: All
    - name: https-home-assistant
      protocol: HTTPS
      port: 443
      hostname: home-assistant.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: home-assistant-tls
            namespace: home-automation
      allowedRoutes:
        namespaces:
          from: All
    - name: https-zigbee2mqtt
      protocol: HTTPS
      port: 443
      hostname: zigbee2mqtt.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: zigbee2mqtt-tls
            namespace: home-automation
      allowedRoutes:
        namespaces:
          from: All
    - name: https-random-gif
      protocol: HTTPS
      port: 443
      hostname: random-gif.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: random-gif-tls
            namespace: random-gif
      allowedRoutes:
        namespaces:
          from: All
    - name: https-uptime-kuma
      protocol: HTTPS
      port: 443
      hostname: uptime.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: uptime-kuma-tls
            namespace: uptime-kuma
      allowedRoutes:
        namespaces:
          from: All
    - name: https-aroma
      protocol: HTTPS
      port: 443
      hostname: aroma.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: aroma-tls
            namespace: aroma
      allowedRoutes:
        namespaces:
          from: All
    - name: https-pb-aroma
      protocol: HTTPS
      port: 443
      hostname: pb-aroma.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: pb-aroma-tls
            namespace: aroma
      allowedRoutes:
        namespaces:
          from: All
    - name: https-umami
      protocol: HTTPS
      port: 443
      hostname: umami.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: umami-tls
            namespace: umami
      allowedRoutes:
        namespaces:
          from: All
    - name: https-zot
      protocol: HTTPS
      port: 443
      hostname: zot.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: zot-tls
            namespace: zot
      allowedRoutes:
        namespaces:
          from: All
    - name: https-lightrag
      protocol: HTTPS
      port: 443
      hostname: lightrag.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lightrag-tls
            namespace: gaspard
      allowedRoutes:
        namespaces:
          from: All
    - name: https-immich
      protocol: HTTPS
      port: 443
      hostname: immich.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: immich-tls
            namespace: immich
      allowedRoutes:
        namespaces:
          from: All
    - name: http-ca-portal
      protocol: HTTP
      port: 80
      hostname: ca.${CLUSTER_DOMAIN}
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
  namespace: kube-system
  annotations:
    io.cilium/lb-ipam-ips: ${LB_EXTERNAL_GATEWAY}
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-auth
      protocol: HTTPS
      port: 443
      hostname: auth.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: authentik-tls
            namespace: authentik
      allowedRoutes:
        namespaces:
          from: All
    - name: https-home-assistant
      protocol: HTTPS
      port: 443
      hostname: home-assistant.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: home-assistant-tls
            namespace: home-automation
      allowedRoutes:
        namespaces:
          from: All
    - name: https-homarr
      protocol: HTTPS
      port: 443
      hostname: homarr.${CLUSTER_DOMAIN}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: homarr-tls
            namespace: homarr
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: internal-http-to-https-redirect
  namespace: kube-system
spec:
  parentRefs:
    - name: internal-gateway
      namespace: kube-system
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-http-to-https-redirect
  namespace: kube-system
spec:
  parentRefs:
    - name: external-gateway
      namespace: kube-system
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
