apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: monitoring
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:ZmpkoMmtpqW3Mrbpea13baIrSH3Vt36x7OJgPFfhBVU=,iv:mRGkInOiZqetsI8TZYnt/sqp3heu4SuL0ybwYkS6PCs=,tag:MHhdmqUth67yZykUL5eSng==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbGhhem1kMVFwMzUvRi9y
        RlRCSFVHKzJlM1ZwWUlhU0FoM2lNMDhadlN3CjlMRThHekN4VGpncyswQ2s5bFJo
        QWtxM2F0MUc2WU9nYmQwMzg0VUhrS00KLS0tIEV3Wi9WVjJ2VXUrOTg5cmtXcWlY
        dVYwWGJLSEQzVExmcWIvMWs2TFhPRzgKEfsaj/PMFRr2dJJGxAZzCaWC/AGOQ35u
        k4RjiE2oE0YSfTmdMv1CClnW/SLXw80QstsFiwlPKvi7rDrHxGGTag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c2tCa2xqdCtBbHNMM2Mv
        N0t6eEg0VkZiaFNyWjRNYldaZGk2VHVsMXprCjVZNlVYMFJSQUMydEcwOWxHaDJv
        K1Z4c2c0OFRMVmRzQ3dYREsvaW9meHcKLS0tICtFQStUcEhSWUF2S1Z6QUU1ajU1
        WlJta09rU0t2NGFVckIyajA3REI5a0EKmd8Gs8AxhquGSZEN13Js53quw2dcs0I1
        USqmCtIyUIznSWP3NvJCWg804VpOepeUzE4LXXsHYYF34LBcMGBKSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-28T22:42:49Z"
  mac: ENC[AES256_GCM,data:JLf7+IZBovOtkuH+ieBSV4yeCP4J9LKGkkg15UiVkHirROrs4w66IRM7wXdDSR/fZz2VJMmzXKl3xzDwl1dfbaZ6fHRq7TQhzQULV7uRJn6fXmREVXqtOMoCeERnnRWseKQQb/DrRZKnemNoNGrlCa4peD19mod9QhD/yeg2Gns=,iv:M6TCXh8jxR39sEY8wxg1EIn+HFkE2pbOeUb21fuGuTg=,tag:9Qb/43H7bRUfNgW2rxhjqA==,type:str]
  version: 3.11.0
