apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:XDn5WgA=,iv:JmI/PoMEk+1Ic5QMFCttAsIXPZRO8+gPd3yXTBKNBBs=,tag:+vXvk2dWq07ylTKgyj4ItQ==,type:str]
  admin-password: ENC[AES256_GCM,data:NHqDQd8zUGmbWjI930J1c4g+DA==,iv:Ip6aY8r1WVf5MuJ3lkr9sPCZPzSp0W83UzM995J7XHY=,tag:3aRU5Tpw86JYBF5Atu3/TQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WlZsd2RHaGlERXRYK3lS
        SFlBbW8zaVQreFVmaDhwemtXTjErVTArb2g0CmQvbEV2QjdUcEp5QTVwakVKaEI5
        akJYTGJHR3AzdHhjTlJYRElFc0UyNzQKLS0tIEJLbEdpYVZ4QVdGYld0TDR4R2NQ
        RGdieTc2Q1pHaTZrWHh2LzNVUGlIZEEKZUmrONZKBc6X0Zir1Y5j6JMz24RTGsQc
        3xYVNWY4l0E6cux4wefTLsCQHRCmxHqLWiuM2+GGLox55g1XOywGVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZnFLMENBWnNhby9qY3E3
        VWx6L1Z5YjcwTlI1TEp4RXRXaTVjRmk0MzJnCk5PdzB4RTBBUTh6OVV5d3FpbkZm
        NTFHYVEwbjZUVmhmVmJkTmtqbUk0YWcKLS0tIEMzcmJXR0dwY3ZCRnRVanFSWGtP
        TWcyaFM5aVdLWm5kbXJsNzFqMlpFVGsKgXGrqsyiz/x39uY/vf4FSmFKINmg4rgG
        ghrNHO8pcvff1HtyxlGcawSjDzWnmdLzDX804RfcAYg0MV25tLAhkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-12-12T20:21:25Z"
  mac: ENC[AES256_GCM,data:vMt9a09MiR3LI4LZA+LzqMMiml9y29B18WuofoOEHQH4jU4H+OpOAW/Z0oh40qyWpln2QLlpA/wVMDtNgv5vfvtKgi5Qj+2KEm6NzSeceNkcorzu5K2jUNHq+CUP+W7gLUe1Nn3rbLwCUoqQGrTBX1U5Wz4tZogR90W0los/t9s=,iv:7SR+ZP/bm8+WqgT4XvAY5WPHEEbIMZVCprzkXDOLTnQ=,tag:wYeVFt0HJN4HkYIiqp3unQ==,type:str]
  version: 3.11.0
