apiVersion: v1
kind: Secret
metadata:
  name: qdrant-secrets
  namespace: qdrant
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:3TswDYgf61/obSudhSdCsacEXBv6DyYhR4TEKXszEzPBf1Y0RStMi9QydyNIkuy2ggv+qOCqodehYaGg3Yw12A==,iv:bYBMFMlL0UJWtHGCcex1d+eF5qKGWSU0crNo65Gpf3w=,tag:nBeeFcu4mUQQz//LjZ3YEQ==,type:str]
  read-only-api-key: ENC[AES256_GCM,data:FUVfPDHTAXtNe27qB6lx0d9ZsiP8lcNDADCzr1wWPUrCK09Vgs40yaMWylqN6xSv/1auMDeN39vRSXAFMIy/HQ==,iv:RSA6TwvC83Z2Z9EzQP9USDM0SKIdQaRi+vrPZFy/jIw=,tag:+LtYnk9bVac16NsZdI6taQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseVBvQytwdTFLN2FIeThM
        Q2t5SFJQTnBIcUR1SWRTeXNNakZ0TE9MNkE0CmJhMU83YmZzYjA0TnF4RlBmUlFx
        b2x0c0F4WjFnRU53Qm42Rk5ZSjVvT3cKLS0tIFRrZEVvSlI2VVRmay9rUjI4THhu
        ZzZrc0xUOU92S0hHWjNBNGJzYytoUU0KjNmv33nZ6Zs9YvkME86AN5w0uneNVAVR
        ueZKHbk1zm6vlyBdCHn+5olVgynhgHMg5kWuu1UIsJTO3N53ZT+WvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSE1TdEI4dHFlRVU1QmUw
        ZGo3alBBcTRmVkNjSkxMVFBTdlhEbFl0em1VCjF6OEZteXVxdVR2Szc1azNTY0Vm
        Y0RSTHpxUGU4SW9WdG9wam16SjlhaEUKLS0tIEJDNytwWERpbm1pVjlYK1FnZUY4
        MTVlSHhTekE5Q283STJLYVRwWFpRbUkKQgfgl5olUhaGc2+/ES/JVdcD7lwmOj63
        g7lW6GAjZL1yWoMB16DaFeF30ByjfW7RcFWsctFK8Su94iOj5jUirw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-25T12:52:38Z"
  mac: ENC[AES256_GCM,data:O5sjz+cebVBnxwl2fZ2Szw6+G3x9jlORbsXqGrkFMmoZg7BP5B5tymJeMBBc64Vu+jPQR3W05CsVeT8YX3PAQNs7mCguccbmouqT4+6ruk9/XjGOHoKLhoPub+HePW9E1lI/DKxzZD2EaUdsNye5kIqcqhqzvB/btMM8FStGGYM=,iv:GYcklAKOfdE3gTIMB/sa+L3rC7wTFlL5CWmHGm1Qnx4=,tag:sv5mVlyBnggjXKL/BfxqGA==,type:str]
  version: 3.12.2
