apiVersion: v1
kind: Secret
metadata:
  name: qdrant-secrets
  namespace: qdrant
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:3TswDYgf61/obSudhSdCsacEXBv6DyYhR4TEKXszEzPBf1Y0RStMi9QydyNIkuy2ggv+qOCqodehYaGg3Yw12A==,iv:bYBMFMlL0UJWtHGCcex1d+eF5qKGWSU0crNo65Gpf3w=,tag:nBeeFcu4mUQQz//LjZ3YEQ==,type:str]
  read-only-api-key: ENC[AES256_GCM,data:FUVfPDHTAXtNe27qB6lx0d9ZsiP8lcNDADCzr1wWPUrCK09Vgs40yaMWylqN6xSv/1auMDeN39vRSXAFMIy/HQ==,iv:RSA6TwvC83Z2Z9EzQP9USDM0SKIdQaRi+vrPZFy/jIw=,tag:+LtYnk9bVac16NsZdI6taQ==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMmNVblJpNVhGTk1uNzRm
        d1YxZzU4TUppR05SNE80aFdwQVRnb3cvQ3dFCmY4c0FpTXFzTityeVZSSUhucXM3
        YjVpS1VoR2loVHJ3U3g3UGdZNHdmcncKLS0tIEt2b3ZXQjl1SmE1Z1NnZU01T0NH
        Nk0xS0JZS0xLc3VLQmI2U0lneWJyT0EKxU5Cg+vbhqZuN4V9u2C4OSvdg17GUiwW
        tjy4070DXF3YOzCroIouv5/FYvy4uT3OcLFrvZ8XldEpWegDyionnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T12:52:38Z"
  mac: ENC[AES256_GCM,data:O5sjz+cebVBnxwl2fZ2Szw6+G3x9jlORbsXqGrkFMmoZg7BP5B5tymJeMBBc64Vu+jPQR3W05CsVeT8YX3PAQNs7mCguccbmouqT4+6ruk9/XjGOHoKLhoPub+HePW9E1lI/DKxzZD2EaUdsNye5kIqcqhqzvB/btMM8FStGGYM=,iv:GYcklAKOfdE3gTIMB/sa+L3rC7wTFlL5CWmHGm1Qnx4=,tag:sv5mVlyBnggjXKL/BfxqGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
