apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portfolio
  namespace: portfolio
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true

  values:
    controllers:
      portfolio:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            # renovate: datasource=docker depName=ghcr.io/bruno00o/portfolio
            image:
              repository: ghcr.io/bruno00o/portfolio
              tag: latest@sha256:a7a8fcc8d6942c99bc9156a990a723c06b4042cfbb0b700a2bfbb3a4ce30344a
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /
                port: 8080
              readiness:
                enabled: true
                type: HTTP
                path: /
                port: 8080
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 200m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: portfolio
        ports:
          http:
            port: 8080

    persistence:
      nginx-cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
      nginx-run:
        type: emptyDir
        globalMounts:
          - path: /var/run
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
