apiVersion: v1
kind: Secret
metadata:
  name: zot-pull
  namespace: doublons
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:N38rvQ1N8agwQEy+N3BnYq4zZjfsS2aXpMH6O2L8mJAApvWLvtASpfHc8GfEpUpx4fuD5uSh9/GP6k0DYc41VvHd8fEEMPhccTpf4g/aOW7Z3wA9p2oEplpDRTguOVPPNbHBberlDRKBsk9sEAk3G+MMqoixqfvCmmsMQ/ZVhZsGJZn48p4+9PbmzrLnu0ecAE2F+hoe/SF7YnIv3+8VrrdBFAywkfES4CjYKSuDEFI362q4jfruSHPCQTFgZO1OFKqCHzKLthK2LrfgRndjA75w9uhM5fpIX5tV6mrKA/f3TC3jd+7xTnQItw7Kp3AOLFzfzzhs2clNeoGSW8FUUN76rYsHpDx/1brd11wzmG4swA6Cd9m7gMQRJrZencBNy5FgBkpyRScvXOhc4EOR0jRI7WFXyFFi4OCss6MsBzUjhVitzENvrPAWJ4SB48qsk5Q=,iv:5hbOs7nGQPoAMuUFvQYHezPyfcufaaUKCCFOYLJqth0=,tag:6ML2QPUJNF0+daCjixqmog==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aGVVNCsyQUtHeVc0Q2FO
        UThDSTlIV2NndUpwWDA1eEszSGtUQlVLc1ZFCllYN2JEZ2diQXAwQi9FK0V5cDNn
        YWhUbE4vM3VWbUR0VlFtUEdLV2dJZm8KLS0tIDVrSElJMGoxSCtRWFJyL2JsNDZJ
        cmZMVDJRRUt6RzJocmxWQnVPRVc2d28K+ei20hpsQAJkQqrggxImEF98ZjuBiVAI
        IO/x89qFAtUsozif0CzVJTsGQXehJA9u6+DMULkA/fdxbcIep7jFlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdUF5WjJGWkZEZDVvbUFO
        VVZ4K2pzLzlZSnRaaW5welRkYTJRNFBlUFJnCi92eVBxUjI0dTNRZThwK3BpeHZz
        NHRjdkxlSHJ2QWZhVWFjSTh2aGx1UGMKLS0tIEVXNURPaDBLTnovaDVNb1RENG01
        VGJDcDg1cHExbysvZ2xBUmN5NjltSU0KaWO0DeP8i6g5C/3Xip6D5Ltv7R9CynLt
        wv9yW4SbGfTO3FmivXVsYfffBr0YSpdHVUsZaN6c5urGi0vfU9HEtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T12:32:46Z"
  mac: ENC[AES256_GCM,data:1bxwxTMveexq/3hCuklXAgtUOJAkgfsh2ny2bC5ZKrgbEnNNgnU3gs6G535z56RmdRtIZmXDWYxqQhwQH/EwFa3s7Fs4eeiMtlZUHWRtH1Z+O3GWATr7ilmM4gEaQ/7VYwQ1G1ZZLfH0hHnRdp4FZ3ebk4nIamSDyPJT7o48aQ8=,iv:zFnXtoy/4vUYv+afS2hV1O9tDr2tJE9hki0WwPMChvA=,tag:MoBo8r4+SrwhNygAcAYR9A==,type:str]
  version: 3.13.3
