apiVersion: v1
kind: Secret
metadata:
  name: zot-pull
  namespace: doublons
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:bGKKBnEFTcd/2MNcnxvI3aCK6vjYBwU2ZajugpkehiTPNdTLdwqvbhNyFZdbqf9vkpJ380HUAvNSceMzZd0ZboRtFI3WEFRZv/+rbzFdFmkj2i2fu5tfRyYUzr1JILUShRz2GAVzxOxlvuOZjWydpDiThrdbwd7EiZ6iIWqBZdJM9wk8s8Y3L7SCasjhwbXXjZWdtzz03a5jqjk0sNat9PboBRj1Q6ptSQ==,iv:nG7GUXZroaIicfLBADecgxF6m2iXZHCQoxhRJb64Tag=,tag:zpTBk1oHq2eCa6eDU6h5eg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTTNYbkc0dWFvUmFKVWIx
        UHpTL1lVTGs2WHM5SjRRYnRIVzRvZm5TTmdvClVHVW5YUEtUNmdxS1BrSWNtOHVs
        RUt0ajRhY2xaS2NJQW1ZR1Y4TkdOZG8KLS0tIEhLLzZEcDVrVVBJQTB2OG1UUlZp
        MWk5UGdUMy8vR1RCV1ZHK0VCZ1ZDQ2cKdg1XD2Ak32EHx1FSIXWua2tlonjNBHP8
        1uoarYUd/zXJMJxD7t7nAl/Xi5JMU8lpfzjkIaZEgaySPVniVGwQjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdWU3Qjg4VEVQV1hvR09X
        SXhKL2tOdnN1a3h1bkJqN04vSXZLUFQ4VXhrCmlybEpqSGdJQno1VXBzdHZUbEIr
        akVId0lxczNuR3QxdXRpMi9sRjlsMEkKLS0tIE1JRHRieXE4QXFGMFJLSWxsOHEy
        dmJlVmh1RGdQZ0tEcXZ2Z0ZadFYzS1UKytZkVt1cCKUhtONIHzmgeHTYiY+IcaJt
        XFX/YQeGvJDCbBb5ElZ5lS5oRMOR3oal7V26iQGs+/7A1SmkRkk2xA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wx3xdwl20yvywlhnzlfdv03eaz73ye26ryrrm4afsehh9psc63tq5supkm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T22:01:47Z"
  mac: ENC[AES256_GCM,data:N858yd5mTssgE59bMmSDVoXQFNPPiL+LNUfC2Pe36fabmAQ5igBD9jSZ5wjloi07qMWHAfD6buBaRxXTSbPGyhdzirOdqBytITxeZXa68PA1RzoCkARFUtYy6Kx/T2awZkkYhRmpEarPi5cMVdZEPEQ6BrTZ1DKo6teJhgt9E2w=,iv:llhvzLVjYKza8N9eN372FOShLL6ntlteKKEny7GVans=,tag:4OJXUN6jO6pE9toLV1bN1Q==,type:str]
  version: 3.12.2
