apiVersion: v1
kind: Secret
metadata:
  name: zot-pull
  namespace: doublons
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:bGKKBnEFTcd/2MNcnxvI3aCK6vjYBwU2ZajugpkehiTPNdTLdwqvbhNyFZdbqf9vkpJ380HUAvNSceMzZd0ZboRtFI3WEFRZv/+rbzFdFmkj2i2fu5tfRyYUzr1JILUShRz2GAVzxOxlvuOZjWydpDiThrdbwd7EiZ6iIWqBZdJM9wk8s8Y3L7SCasjhwbXXjZWdtzz03a5jqjk0sNat9PboBRj1Q6ptSQ==,iv:nG7GUXZroaIicfLBADecgxF6m2iXZHCQoxhRJb64Tag=,tag:zpTBk1oHq2eCa6eDU6h5eg==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUklITFcySDJyMW1RVkVm
        bjc4K091b2tKb0FMMDk1L1g0aFZ5YmI1RWhBCkliNElDZ3RZZnpTaUExL1F3RmNK
        Umc4Z01qTlZwVDlRZ0tlQUJ3UzVVSzAKLS0tIDVaUGlOWDlhUXBkbmUxd3ZHR0hr
        Q0hyc1ZKV0I2MGpUOFJaai9ycVpGS1UKhkZxVUHqwCVOO0HEqNmfLUsNJI7dV6b2
        kgVv4MgDupv57P4z9VjidB0vG8nGCJ3yvD3z9b3jgc9Dq3lM4pCp7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T22:01:47Z"
  mac: ENC[AES256_GCM,data:N858yd5mTssgE59bMmSDVoXQFNPPiL+LNUfC2Pe36fabmAQ5igBD9jSZ5wjloi07qMWHAfD6buBaRxXTSbPGyhdzirOdqBytITxeZXa68PA1RzoCkARFUtYy6Kx/T2awZkkYhRmpEarPi5cMVdZEPEQ6BrTZ1DKo6teJhgt9E2w=,iv:llhvzLVjYKza8N9eN372FOShLL6ntlteKKEny7GVans=,tag:4OJXUN6jO6pE9toLV1bN1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
